/* PlayOneVideo — website i18n */
(function () {
  const LANGS = {
    en: 'English', nl: 'Nederlands', de: 'Deutsch', fr: 'Français',
    es: 'Español', it: 'Italiano', pt: 'Português', ru: 'Русский',
    ar: 'العربية', zh: '中文', ja: '日本語', ko: '한국어',
    hi: 'हिन्दी', id: 'Bahasa Indonesia',
  };

  const T = {
    /* ── nav ── */
    navAffiliate: { en:'Affiliate', nl:'Word affiliate', de:'Affiliate', fr:'Affilié', es:'Afiliado', it:'Affiliato', pt:'Afiliado', ru:'Партнёрство', ar:'شراكة', zh:'推广合作', ja:'アフィリエイト', ko:'제휴', hi:'सहयोगी', id:'Afiliasi' },
    navPrivacy:   { en:'Privacy', nl:'Privacy', de:'Datenschutz', fr:'Confidentialité', es:'Privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'الخصوصية', zh:'隐私', ja:'プライバシー', ko:'개인정보', hi:'गोपनीयता', id:'Privasi' },
    navTerms:     { en:'Terms', nl:'Voorwaarden', de:'AGB', fr:'CGU', es:'Términos', it:'Termini', pt:'Termos', ru:'Условия', ar:'الشروط', zh:'条款', ja:'利用規約', ko:'이용약관', hi:'शर्तें', id:'Syarat' },

    /* ── hero ── */
    heroH1:    { en:'Let kids watch one video.', nl:'Laat kinderen één filmpje kijken.', de:'Lass Kinder ein Video ansehen.', fr:'Laissez les enfants regarder une vidéo.', es:'Deja que los niños vean un vídeo.', it:'Lascia che i bambini guardino un video.', pt:'Deixe as crianças assistir um vídeo.', ru:'Позвольте ребёнку посмотреть одно видео.', ar:'دع الأطفال يشاهدون مقطعاً واحداً.', zh:'让孩子看一个视频。', ja:'子供に動画を1本見せよう。', ko:'아이가 영상 하나를 보게 하세요.', hi:'बच्चों को एक वीडियो देखने दें।', id:'Biarkan anak menonton satu video.' },
    heroSub:   { en:'Use YouTube in a child-friendly way.\n\nNo suggestions.\nNo clicking through.\nNo arguments.', nl:'Gebruik YouTube op een kindvriendelijke manier.\n\nGeen suggesties.\nNiet doorklikken.\nGeen ruzie.', de:'Nutze YouTube auf eine kindergerechte Weise.\n\nKeine Vorschläge.\nKein Weiterklicken.\nKein Streit.', fr:'Utilisez YouTube de façon adaptée aux enfants.\n\nPas de suggestions.\nPas de navigation aléatoire.\nPas de disputes.', es:'Usa YouTube de forma adaptada a los niños.\n\nSin sugerencias.\nSin hacer clic en otros.\nSin discusiones.', it:'Usa YouTube in modo adatto ai bambini.\n\nNiente suggerimenti.\nNiente clic su altri video.\nNiente litigi.', pt:'Use o YouTube de forma adequada para crianças.\n\nSem sugestões.\nSem clicar em outros.\nSem brigas.', ru:'Используйте YouTube безопасно для детей.\n\nНикаких рекомендаций.\nНикаких переходов.\nНикаких споров.', ar:'استخدم YouTube بطريقة مناسبة للأطفال.\n\nلا اقتراحات.\nلا نقر على مقاطع أخرى.\nلا جدالات.', zh:'以儿童友好的方式使用YouTube。\n\n没有推荐。\n不乱点击。\n没有争吵。', ja:'子供に安全なYouTubeの使い方。\n\nおすすめなし。\n他の動画へのクリックなし。\n言い争いなし。', ko:'아이에게 안전한 YouTube 사용법。\n\n추천 없음。\n다른 영상 클릭 없음。\n다툼 없음。', hi:'बच्चों के लिए YouTube का सुरक्षित उपयोग।\n\nकोई सुझाव नहीं।\nआगे क्लिक नहीं।\nकोई झगड़ा नहीं।', id:'Gunakan YouTube dengan cara yang ramah anak.\n\nTanpa saran.\nTanpa klik video lain.\nTanpa pertengkaran.' },
    heroPrice: { en:'14 days free, then $1.99 per month. Cancel anytime.', nl:'14 dagen gratis, daarna €1,99 per maand. Opzegbaar wanneer je wilt.', de:'14 Tage kostenlos, dann €1,99 pro Monat. Jederzeit kündbar.', fr:'14 jours gratuits, puis 1,99 €/mois. Annulable à tout moment.', es:'14 días gratis, luego €1,99/mes. Cancela cuando quieras.', it:'14 giorni gratis, poi €1,99/mese. Disdici quando vuoi.', pt:'14 dias grátis, depois R$10,90/mês. Cancele quando quiser.', ru:'14 дней бесплатно, затем 199 ₽ в месяц. Отмена в любое время.', ar:'14 يوماً مجاناً، ثم 7.99 ر.س شهرياً. إلغاء في أي وقت.', zh:'免费14天，之后每月¥18。随时可取消。', ja:'14日間無料、その後月¥300。いつでもキャンセル可。', ko:'14일 무료, 이후 월 ₩3,300. 언제든지 취소 가능.', hi:'14 दिन मुफ्त, फिर ₹160/माह। कभी भी रद्द करें।', id:'14 hari gratis, lalu Rp32.000/bulan. Batalkan kapan saja.' },
    heroComingSoon: { en:'coming soon', nl:'binnenkort', de:'bald verfügbar', fr:'bientôt', es:'próximamente', it:'presto', pt:'em breve', ru:'скоро', ar:'قريباً', zh:'即将推出', ja:'近日公開', ko:'곧 출시', hi:'जल्द आ रहा है', id:'segera hadir' },

    /* ── problem section ── */
    problemLabel: { en:'The problem', nl:'Het probleem', de:'Das Problem', fr:'Le problème', es:'El problema', it:'Il problema', pt:'O problema', ru:'Проблема', ar:'المشكلة', zh:'问题', ja:'問題', ko:'문제', hi:'समस्या', id:'Masalah' },
    problemH2:    { en:'Sound familiar?', nl:'Ken je dit?', de:'Kennt ihr das?', fr:'Ça vous parle ?', es:'¿Te suena?', it:'Ti suona familiare?', pt:'Familiar?', ru:'Узнаёте?', ar:'هل هذا مألوف؟', zh:'听起来熟悉吗？', ja:'よくある話では？', ko:'익숙한 상황인가요?', hi:'पहचाना?', id:'Familiar?' },
    problemBody:  { en:'Your child is allowed to watch 1 video.', nl:'Je kind mag 1 filmpje kijken.', de:'Dein Kind darf 1 Video ansehen.', fr:'Votre enfant a le droit de regarder 1 vidéo.', es:'Tu hijo puede ver 1 vídeo.', it:'Tuo figlio può guardare 1 video.', pt:'Seu filho pode assistir 1 vídeo.', ru:'Ребёнку можно посмотреть 1 видео.', ar:'يُسمح لطفلك بمشاهدة مقطع واحد.', zh:'孩子只能看1个视频。', ja:'子供が見ていいのはビデオ1本だけ。', ko:'아이가 영상 1개만 볼 수 있는데.', hi:'बच्चे को 1 वीडियो देखने की अनुमति है।', id:'Anak Anda boleh menonton 1 video.' },
    calloutLine1: { en:'Scrolls around.', nl:'Scrollt door.', de:'Scrollt weiter.', fr:'Il fait défiler.', es:'Se pone a hacer scroll.', it:'Scorre avanti.', pt:'Fica rolando.', ru:'Листает.', ar:'يتصفّح.', zh:'开始滑屏。', ja:'スクロールしはじめる。', ko:'스크롤하다가.', hi:'स्क्रॉल करता है।', id:'Malah scroll.' },
    calloutLine2: { en:'Clicks away.', nl:'Klikt door.', de:'Klickt weiter.', fr:'Clique sur autre chose.', es:'Hace clic en todo.', it:'Clicca ovunque.', pt:'Fica clicando.', ru:'Кликает дальше.', ar:'ينقر ويتنقّل.', zh:'乱点视频。', ja:'クリックしてしまう。', ko:'이것저것 클릭.', hi:'क्लिक करता है।', id:'Klik sana-sini.' },
    calloutLine3: { en:'Arguments.', nl:'Ruzie.', de:'Streit.', fr:'Disputes.', es:'Discusiones.', it:'Litigi.', pt:'Briga.', ru:'Скандал.', ar:'شجار.', zh:'争吵。', ja:'言い争い。', ko:'다툼.', hi:'झगड़ा।', id:'Bertengkar.' },

    /* ── approach section ── */
    approachLabel: { en:'Our approach', nl:'Onze aanpak', de:'Unser Ansatz', fr:'Notre approche', es:'Nuestro enfoque', it:'Il nostro approccio', pt:'Nossa abordagem', ru:'Наш подход', ar:'مقاربتنا', zh:'我们的方法', ja:'私たちのアプローチ', ko:'우리의 접근법', hi:'हमारा दृष्टिकोण', id:'Pendekatan kami' },
    approachH2:    { en:'All video apps make kids addicted.', nl:'Alle videoapps maken kinderen verslaafd.', de:'Alle Video-Apps machen Kinder süchtig.', fr:'Toutes les applis vidéo rendent les enfants accros.', es:'Todas las apps de vídeo enganchan a los niños.', it:'Tutte le app video creano dipendenza nei bambini.', pt:'Todos os apps de vídeo viciam as crianças.', ru:'Все видеоприложения вызывают зависимость у детей.', ar:'كل تطبيقات الفيديو تُدمن الأطفال.', zh:'所有视频应用都让孩子上瘾。', ja:'すべての動画アプリが子供を依存させる。', ko:'모든 동영상 앱이 아이를 중독시킵니다.', hi:'सभी वीडियो ऐप्स बच्चों को लत लगा देते हैं।', id:'Semua aplikasi video membuat anak kecanduan.' },
    approachBody:  { en:'This app is intentionally boring. It plays one video.', nl:'Deze app is expres saai. Hij speelt één video af.', de:'Diese App ist absichtlich langweilig. Sie spielt ein Video ab.', fr:'Cette appli est volontairement ennuyeuse. Elle joue une seule vidéo.', es:'Esta app es aburrida a propósito. Reproduce un vídeo.', it:'Questa app è volutamente noiosa. Riproduce un solo video.', pt:'Este app é propositalmente chato. Ele toca um vídeo.', ru:'Это приложение намеренно скучное. Оно воспроизводит одно видео.', ar:'هذا التطبيق مُصمَّم ليكون مملاً. يشغّل مقطعاً واحداً فقط.', zh:'这款应用故意设计得无聊。它只播放一个视频。', ja:'このアプリは意図的につまらなく作られています。動画を1本再生するだけです。', ko:'이 앱은 의도적으로 지루하게 만들었습니다. 영상 하나만 재생합니다.', hi:'यह ऐप जानबूझकर नीरस है। यह एक वीडियो चलाता है।', id:'Aplikasi ini sengaja dibuat membosankan. Ia memutar satu video.' },
    feat1Title: { en:'No bright colours', nl:'Geen felle kleuren', de:'Keine grellen Farben', fr:'Pas de couleurs vives', es:'Sin colores llamativos', it:'Nessun colore sgargiante', pt:'Sem cores vivas', ru:'Никаких ярких цветов', ar:'لا ألوان صارخة', zh:'无鲜艳颜色', ja:'派手な色なし', ko:'밝은 색상 없음', hi:'चमकीले रंग नहीं', id:'Tidak ada warna cerah' },
    feat1Body: { en:'Calm interface. Attention on the video, not the app.', nl:'Rustige interface. Aandacht bij het filmpje, niet bij de app.', de:'Ruhige Oberfläche. Aufmerksamkeit auf das Video, nicht auf die App.', fr:'Interface apaisante. Attention sur la vidéo, pas sur l\'appli.', es:'Interfaz tranquila. Atención en el vídeo, no en la app.', it:'Interfaccia tranquilla. Attenzione al video, non all\'app.', pt:'Interface calma. Atenção no vídeo, não no app.', ru:'Спокойный интерфейс. Внимание на видео, а не на приложении.', ar:'واجهة هادئة. التركيز على الفيديو، لا على التطبيق.', zh:'平静的界面。注意力放在视频上，而非应用。', ja:'落ち着いたインターフェース。注意はアプリではなく動画へ。', ko:'차분한 인터페이스. 앱이 아닌 영상에 집중.', hi:'शांत इंटरफेस। ध्यान वीडियो पर, ऐप पर नहीं।', id:'Antarmuka tenang. Perhatian pada video, bukan aplikasi.' },
    feat2Title: { en:'No animations', nl:'Geen animaties', de:'Keine Animationen', fr:'Pas d\'animations', es:'Sin animaciones', it:'Nessuna animazione', pt:'Sem animações', ru:'Никакой анимации', ar:'لا رسوم متحركة', zh:'无动画', ja:'アニメーションなし', ko:'애니메이션 없음', hi:'कोई एनिमेशन नहीं', id:'Tidak ada animasi' },
    feat2Body: { en:'Nothing that stimulates or distracts.', nl:'Niets dat prikkelt of afleidt.', de:'Nichts, das stimuliert oder ablenkt.', fr:'Rien qui stimule ou distrait.', es:'Nada que estimule o distraiga.', it:'Niente che stimoli o distragga.', pt:'Nada que estimule ou distraia.', ru:'Ничего, что стимулирует или отвлекает.', ar:'لا شيء يُحفّز أو يُشتّت.', zh:'没有任何刺激或分散注意力的东西。', ja:'刺激したり気を散らすものは何もない。', ko:'자극하거나 산만하게 만드는 것 없음.', hi:'कोई उत्तेजना या विकर्षण नहीं।', id:'Tidak ada yang merangsang atau mengalihkan perhatian.' },
    feat3Title: { en:'No scores or rewards', nl:'Geen scores of beloningen', de:'Keine Punkte oder Belohnungen', fr:'Pas de scores ni de récompenses', es:'Sin puntuaciones ni recompensas', it:'Nessun punteggio o premio', pt:'Sem pontuações ou recompensas', ru:'Никаких очков или наград', ar:'لا نقاط ولا مكافآت', zh:'无得分或奖励', ja:'得点も報酬もなし', ko:'점수나 보상 없음', hi:'कोई स्कोर या पुरस्कार नहीं', id:'Tidak ada skor atau hadiah' },
    feat3Body: { en:'No likes, streaks or points to come back for.', nl:'Geen likes, streaks of punten om op terug te komen.', de:'Keine Likes, Streaks oder Punkte, die zum Wiederkommen verleiten.', fr:'Pas de likes, séries ou points pour revenir.', es:'Sin me gusta, rachas ni puntos para volver.', it:'Nessun like, serie o punto per tornare.', pt:'Sem curtidas, sequências ou pontos para voltar.', ru:'Никаких лайков, серий или очков, ради которых хочется вернуться.', ar:'لا إعجابات ولا سلاسل ولا نقاط تجعلك تعود.', zh:'没有点赞、连续天数或积分让你回来。', ja:'戻ってくる理由となるいいね！、ストリーク、ポイントなし。', ko:'다시 오게 만드는 좋아요, 연속 기록, 포인트 없음.', hi:'वापस आने के लिए कोई लाइक, स्ट्रीक या पॉइंट नहीं।', id:'Tidak ada suka, streak, atau poin untuk kembali.' },
    feat4Title: { en:'Intentionally boring', nl:'Expres saai', de:'Absichtlich langweilig', fr:'Volontairement ennuyeux', es:'Aburrida a propósito', it:'Volutamente noioso', pt:'Propositalmente chato', ru:'Намеренно скучное', ar:'مملّ عمداً', zh:'故意无聊', ja:'意図的につまらない', ko:'의도적으로 지루한', hi:'जानबूझकर नीरस', id:'Sengaja membosankan' },
    feat4Body: { en:'Designed to be as little addictive as possible.', nl:'Ontworpen om zo min mogelijk verslavend te zijn.', de:'Entworfen, um so wenig wie möglich süchtig zu machen.', fr:'Conçu pour être le moins addictif possible.', es:'Diseñada para ser lo menos adictiva posible.', it:'Progettato per essere il meno possibile dipendente.', pt:'Projetado para ser o menos viciante possível.', ru:'Разработано так, чтобы вызывать как можно меньше зависимости.', ar:'مُصمَّم ليكون أقل إدماناً ممكناً.', zh:'设计上尽可能减少成瘾性。', ja:'できる限り依存性が少なくなるよう設計されています。', ko:'최대한 중독성이 없도록 설계되었습니다.', hi:'यथासंभव कम नशे की लत के लिए डिज़ाइन किया गया।', id:'Dirancang untuk sesedikit mungkin membuat kecanduan.' },

    /* ── how it works ── */
    howLabel: { en:'How it works', nl:'Hoe het werkt', de:'So funktioniert\'s', fr:'Comment ça marche', es:'Cómo funciona', it:'Come funziona', pt:'Como funciona', ru:'Как это работает', ar:'كيف يعمل', zh:'如何运作', ja:'使い方', ko:'작동 방식', hi:'यह कैसे काम करता है', id:'Cara kerjanya' },
    howH2:    { en:'It\'s that simple.', nl:'Zo simpel is het.', de:'So einfach ist das.', fr:'C\'est aussi simple que ça.', es:'Así de sencillo.', it:'È così semplice.', pt:'É simples assim.', ru:'Всё просто.', ar:'الأمر بهذه البساطة.', zh:'就是这么简单。', ja:'それだけシンプル。', ko:'이렇게 간단합니다.', hi:'बस इतना ही सरल।', id:'Sesederhana itu.' },
    step1: { en:'Select a video', nl:'Klik een filmpje aan', de:'Video auswählen', fr:'Choisir une vidéo', es:'Elige un vídeo', it:'Seleziona un video', pt:'Escolha um vídeo', ru:'Выберите видео', ar:'اختر مقطعاً', zh:'选择一个视频', ja:'動画を選ぶ', ko:'영상 선택', hi:'एक वीडियो चुनें', id:'Pilih video' },
    step2: { en:'Child watches calmly', nl:'Kind kijkt rustig', de:'Kind schaut ruhig', fr:'L\'enfant regarde tranquillement', es:'El niño mira tranquilo', it:'Il bambino guarda tranquillo', pt:'A criança assiste calmamente', ru:'Ребёнок спокойно смотрит', ar:'يشاهد الطفل بهدوء', zh:'孩子安静地观看', ja:'子供が落ち着いて見る', ko:'아이가 조용히 시청', hi:'बच्चा शांति से देखता है', id:'Anak menonton dengan tenang' },
    step3: { en:'Screen goes black', nl:'Scherm wordt zwart', de:'Bildschirm wird schwarz', fr:'L\'écran devient noir', es:'La pantalla se vuelve negra', it:'Lo schermo diventa nero', pt:'A tela fica preta', ru:'Экран гаснет', ar:'تسودّ الشاشة', zh:'屏幕变黑', ja:'画面が暗くなる', ko:'화면이 꺼짐', hi:'स्क्रीन काली हो जाती है', id:'Layar menjadi hitam' },

    /* ── design section ── */
    designLabel: { en:'Design', nl:'Ontwerp', de:'Design', fr:'Design', es:'Diseño', it:'Design', pt:'Design', ru:'Дизайн', ar:'التصميم', zh:'设计', ja:'デザイン', ko:'디자인', hi:'डिज़ाइन', id:'Desain' },
    designH2:   { en:'Intentionally boring.', nl:'Expres saai.', de:'Absichtlich langweilig.', fr:'Volontairement ennuyeux.', es:'Aburrida a propósito.', it:'Volutamente noioso.', pt:'Propositalmente chato.', ru:'Намеренно скучное.', ar:'مملّ عمداً.', zh:'故意无聊。', ja:'意図的につまらない。', ko:'의도적으로 지루한.', hi:'जानबूझकर नीरस।', id:'Sengaja membosankan.' },
    designBody: { en:'No bright colours. No animations. No scores or rewards.\n\nThe interface does not stimulate, so attention stays on the video and not on the app. The app is designed to be as little addictive as possible.', nl:'Geen felle kleuren. Geen animaties. Geen scores of beloningen.\n\nDe interface prikkelt niet, zodat de aandacht bij het filmpje blijft en niet bij de app. De app is ontworpen om zo min mogelijk verslavend te zijn.', de:'Keine grellen Farben. Keine Animationen. Keine Punkte oder Belohnungen.\n\nDie Oberfläche stimuliert nicht, sodass die Aufmerksamkeit beim Video bleibt und nicht bei der App.', fr:'Pas de couleurs vives. Pas d\'animations. Pas de scores ni de récompenses.\n\nL\'interface ne stimule pas, l\'attention reste sur la vidéo et non sur l\'appli.', es:'Sin colores llamativos. Sin animaciones. Sin puntuaciones ni recompensas.\n\nLa interfaz no estimula, la atención se queda en el vídeo.', it:'Nessun colore sgargiante. Nessuna animazione. Nessun punteggio o premio.\n\nL\'interfaccia non stimola, l\'attenzione rimane sul video.', pt:'Sem cores vivas. Sem animações. Sem pontuações ou recompensas.\n\nA interface não estimula, a atenção fica no vídeo.', ru:'Никаких ярких цветов. Никакой анимации. Никаких очков или наград.\n\nИнтерфейс не стимулирует, поэтому внимание остаётся на видео.', ar:'لا ألوان صارخة. لا رسوم متحركة. لا نقاط ولا مكافآت.\n\nالواجهة لا تُحفّز، لذا يبقى التركيز على الفيديو.', zh:'无鲜艳颜色。无动画。无得分或奖励。\n\n界面不会刺激感官，注意力保持在视频上。', ja:'派手な色なし。アニメーションなし。得点も報酬もなし。\n\nインターフェースは刺激しないため、注意が動画に向けられます。', ko:'밝은 색상 없음. 애니메이션 없음. 점수나 보상 없음.\n\n인터페이스가 자극하지 않아 주의가 영상에 집중됩니다.', hi:'कोई चमकीले रंग नहीं। कोई एनिमेशन नहीं। कोई स्कोर या पुरस्कार नहीं।\n\nइंटरफेस उत्तेजित नहीं करता, ध्यान वीडियो पर रहता है।', id:'Tidak ada warna cerah. Tidak ada animasi. Tidak ada skor atau hadiah.\n\nAntarmuka tidak merangsang, perhatian tetap pada video.' },

    /* ── family section ── */
    familyLabel: { en:'Family', nl:'Gezin', de:'Familie', fr:'Famille', es:'Familia', it:'Famiglia', pt:'Família', ru:'Семья', ar:'العائلة', zh:'家庭', ja:'家族', ko:'가족', hi:'परिवार', id:'Keluarga' },
    familyH2:   { en:'Share lists between partners.', nl:'Deel lijsten tussen partners.', de:'Listen zwischen Partnern teilen.', fr:'Partagez les listes entre partenaires.', es:'Comparte listas entre parejas.', it:'Condividi le liste tra partner.', pt:'Compartilhe listas entre parceiros.', ru:'Делитесь списками между партнёрами.', ar:'شارك القوائم بين الوالدين.', zh:'在伴侣之间共享列表。', ja:'パートナー間でリストを共有。', ko:'파트너 간 목록 공유.', hi:'साझेदारों के बीच सूचियां साझा करें।', id:'Bagikan daftar antar pasangan.' },
    familyBody: { en:'Link your partner\'s phone via QR code. Your children\'s favourite videos are automatically shared between you, always up-to-date on both devices.\n\nYour subscription covers the whole family — your partner benefits too.', nl:'Koppel de telefoon van je partner via een QR-code. De favoriete filmpjes van je kinderen worden automatisch gedeeld tussen jullie, op beide toestellen altijd up-to-date.\n\nJe abonnement geldt voor het hele gezin, ook je partner profiteert ervan.', de:'Verbinde das Smartphone deines Partners via QR-Code. Die Lieblingsvideos eurer Kinder werden automatisch geteilt.\n\nDein Abo gilt für die ganze Familie.', fr:'Liez le téléphone de votre partenaire via QR code. Les vidéos préférées de vos enfants sont partagées automatiquement.\n\nVotre abonnement couvre toute la famille.', es:'Vincula el teléfono de tu pareja mediante QR. Los vídeos favoritos de vuestros hijos se comparten automáticamente.\n\nVuestra suscripción cubre toda la familia.', it:'Collega il telefono del tuo partner via QR. I video preferiti dei tuoi figli sono condivisi automaticamente.\n\nL\'abbonamento vale per tutta la famiglia.', pt:'Vincule o celular do seu parceiro via QR. Os vídeos favoritos das crianças são compartilhados automaticamente.\n\nSua assinatura cobre toda a família.', ru:'Подключите телефон партнёра по QR-коду. Любимые видео детей автоматически синхронизируются.\n\nПодписка распространяется на всю семью.', ar:'اربط هاتف شريكك عبر رمز QR. تتم مشاركة مقاطع الأطفال المفضلة تلقائياً.\n\nاشتراكك يشمل العائلة بأكملها.', zh:'通过二维码连接伴侣的手机。孩子的最爱视频自动共享，两台设备始终同步。\n\n您的订阅适用于整个家庭。', ja:'QRコードでパートナーのスマホと接続。子供のお気に入り動画が自動で共有されます。\n\nサブスクリプションは家族全員に有効です。', ko:'QR코드로 파트너 휴대폰을 연결하세요. 아이들의 즐겨찾기 영상이 자동으로 공유됩니다.\n\n구독은 온 가족이 사용 가능합니다.', hi:'QR कोड के जरिए अपने साथी का फोन लिंक करें। बच्चों के पसंदीदा वीडियो स्वचालित रूप से साझा होते हैं।\n\nआपकी सदस्यता पूरे परिवार के लिए है।', id:'Hubungkan ponsel pasangan Anda via QR. Video favorit anak-anak dibagikan secara otomatis.\n\nLangganan Anda berlaku untuk seluruh keluarga.' },

    /* ── boring/approach section ── */
    boringLabel:   { en:'Our approach', nl:'Onze aanpak', de:'Unser Ansatz', fr:'Notre approche', es:'Nuestro enfoque', it:'Il nostro approccio', pt:'Nossa abordagem', ru:'Наш подход', ar:'نهجنا', zh:'我们的理念', ja:'私たちのアプローチ', ko:'우리의 접근법', hi:'हमारा दृष्टिकोण', id:'Pendekatan kami' },
    boringH2:      { en:'This app is boring. On purpose.', nl:'Deze app is saai. En dat is expres.', de:'Diese App ist langweilig. Absichtlich.', fr:'Cette app est ennuyeuse. Exprès.', es:'Esta app es aburrida. A propósito.', it:'Questa app è noiosa. Di proposito.', pt:'Este app é chato. De propósito.', ru:'Это приложение скучное. Намеренно.', ar:'هذا التطبيق ممل. عن قصد.', zh:'这个应用很无聊。故意的。', ja:'このアプリは退屈です。意図的に。', ko:'이 앱은 지루합니다. 의도적으로.', hi:'यह ऐप उबाऊ है। जानबूझकर।', id:'Aplikasi ini membosankan. Sengaja.' },
    boringSub:     { en:"All video apps are addictive. This one isn't.", nl:'Alle videoapps zijn verslavend. Deze niet.', de:'Alle Video-Apps sind süchtig machend. Diese nicht.', fr:'Toutes les apps vidéo créent une dépendance. Pas celle-ci.', es:'Todas las apps de vídeo son adictivas. Esta no.', it:'Tutte le app video creano dipendenza. Questa no.', pt:'Todos os apps de vídeo são viciantes. Este não.', ru:'Все видеоприложения вызывают зависимость. Это — нет.', ar:'جميع تطبيقات الفيديو مُسبِّبة للإدمان. هذا لا.', zh:'所有视频应用都令人上瘾。这个不会。', ja:'すべての動画アプリは依存性があります。このアプリは違います。', ko:'모든 동영상 앱은 중독성이 있습니다. 이 앱은 아닙니다.', hi:'सभी वीडियो ऐप्स नशे की लत हैं। यह नहीं।', id:'Semua aplikasi video membuat ketagihan. Yang ini tidak.' },
    strikeNotif:   { en:'No notifications', nl:'Geen notificaties', de:'Keine Benachrichtigungen', fr:'Pas de notifications', es:'Sin notificaciones', it:'Nessuna notifica', pt:'Sem notificações', ru:'Без уведомлений', ar:'لا إشعارات', zh:'无推送通知', ja:'通知なし', ko:'알림 없음', hi:'कोई सूचना नहीं', id:'Tanpa notifikasi' },
    strikeColors:  { en:'No bright colours', nl:'Geen felle kleuren', de:'Keine grellen Farben', fr:'Pas de couleurs vives', es:'Sin colores llamativos', it:'Nessun colore vivace', pt:'Sem cores chamativas', ru:'Без ярких цветов', ar:'لا ألوان صاخبة', zh:'无鲜艳色彩', ja:'派手な色なし', ko:'화려한 색상 없음', hi:'कोई चमकीले रंग नहीं', id:'Tanpa warna mencolok' },
    strikeScores:  { en:'No scores or rewards', nl:'Geen scores of beloningen', de:'Keine Punkte oder Belohnungen', fr:'Pas de scores ni récompenses', es:'Sin puntuaciones ni recompensas', it:'Nessun punteggio o ricompensa', pt:'Sem pontuações ou recompensas', ru:'Без очков и наград', ar:'لا نقاط ولا مكافآت', zh:'无积分或奖励', ja:'スコアや報酬なし', ko:'점수나 보상 없음', hi:'कोई स्कोर या पुरस्कार नहीं', id:'Tanpa skor atau hadiah' },
    strikeAddiction: { en:'No addictive elements', nl:'Geen verslavingselementen', de:'Keine Sucht-Elemente', fr:'Pas d\'éléments addictifs', es:'Sin elementos adictivos', it:'Nessun elemento che crea dipendenza', pt:'Sem elementos viciantes', ru:'Без элементов зависимости', ar:'لا عناصر إدمانية', zh:'无成瘾元素', ja:'依存性の要素なし', ko:'중독성 요소 없음', hi:'कोई लत लगाने वाले तत्व नहीं', id:'Tanpa elemen adiktif' },

    /* ── no data section ── */
    noDataLabel:    { en:'Privacy', nl:'Privacy', de:'Datenschutz', fr:'Confidentialité', es:'Privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'الخصوصية', zh:'隐私', ja:'プライバシー', ko:'개인정보', hi:'गोपनीयता', id:'Privasi' },
    noDataH2:       { en:"We don't want your data.", nl:'Wij willen jouw data niet.', de:'Wir wollen deine Daten nicht.', fr:'Nous ne voulons pas de vos données.', es:'No queremos tus datos.', it:'Non vogliamo i tuoi dati.', pt:'Não queremos os seus dados.', ru:'Нам не нужны ваши данные.', ar:'لا نريد بياناتك.', zh:'我们不需要你的数据。', ja:'あなたのデータは必要ありません。', ko:'당신의 데이터가 필요 없습니다.', hi:'हमें आपका डेटा नहीं चाहिए।', id:'Kami tidak menginginkan data Anda.' },
    noDataSub:      { en:"And definitely not your child's.", nl:'En zeker niet die van je kind.', de:'Und schon gar nicht die deines Kindes.', fr:"Et surtout pas celles de votre enfant.", es:'Y definitivamente no los de tu hijo.', it:'E tantomeno quelli di tuo figlio.', pt:'E definitivamente não os do seu filho.', ru:'И уж точно не данные вашего ребёнка.', ar:'وبالتأكيد ليس بيانات طفلك.', zh:'更不需要你孩子的。', ja:'お子さんのデータも絶対に。', ko:'자녀의 데이터도 절대 필요 없습니다.', hi:'और बिल्कुल भी आपके बच्चे का नहीं।', id:'Apalagi data anak Anda.' },
    noDataBody:     { en:"We store just a user ID, a nickname for your kid and their favourite videos. That's it.", nl:"We slaan alleen een gebruikersnummer, een bijnaam voor je kind en zijn of haar favoriete video's op. Dat is alles.", de:'Wir speichern nur eine Benutzer-ID, einen Spitznamen für dein Kind und seine Lieblingsvideos. Das war es.', fr:"Nous stockons uniquement un identifiant, un surnom pour votre enfant et ses vidéos préférées. C'est tout.", es:'Solo guardamos un ID de usuario, un apodo para tu hijo y sus videos favoritos. Eso es todo.', it:"Salviamo solo un ID utente, un soprannome per tuo figlio e i suoi video preferiti. Tutto qui.", pt:'Armazenamos apenas um ID de usuário, um apelido para seu filho e seus vídeos favoritos. Só isso.', ru:'Мы храним только идентификатор пользователя, псевдоним ребёнка и его любимые видео. Всё.', ar:'نحتفظ فقط بمعرّف المستخدم ولقب طفلك وفيديوهاته المفضلة. هذا كل شيء.', zh:'我们只保存一个用户ID、孩子的昵称和他的收藏视频。仅此而已。', ja:'ユーザーID、お子さんのニックネーム、お気に入り動画だけを保存します。それだけです。', ko:'사용자 ID, 자녀의 닉네임, 좋아하는 동영상만 저장합니다. 그게 전부입니다.', hi:'हम केवल एक यूजर ID, बच्चे का उपनाम और पसंदीदा वीडियो सहेजते हैं। बस इतना ही।', id:'Kami hanya menyimpan ID pengguna, nama panggilan anak, dan video favorit mereka. Itu saja.' },

    /* ── CTA ── */
    ctaH2:  { en:'Ready to start?', nl:'Klaar om te beginnen?', de:'Bereit loszulegen?', fr:'Prêt à commencer ?', es:'¿Listo para empezar?', it:'Pronto per iniziare?', pt:'Pronto para começar?', ru:'Готовы начать?', ar:'مستعد للبدء؟', zh:'准备好了吗？', ja:'始める準備はできていますか？', ko:'시작할 준비가 됐나요?', hi:'शुरू करने के लिए तैयार हैं?', id:'Siap memulai?' },
    ctaBody: { en:'Add your first child and choose a video. Just one.', nl:'Voeg je eerste kind toe en kies een video. Gewoon één.', de:'Füge dein erstes Kind hinzu und wähle ein Video. Nur eines.', fr:'Ajoutez votre premier enfant et choisissez une vidéo. Une seule.', es:'Añade tu primer hijo y elige un vídeo. Solo uno.', it:'Aggiungi il tuo primo figlio e scegli un video. Solo uno.', pt:'Adicione seu primeiro filho e escolha um vídeo. Apenas um.', ru:'Добавьте первого ребёнка и выберите видео. Всего одно.', ar:'أضف طفلك الأول واختر مقطعاً. واحداً فقط.', zh:'添加您的第一个孩子并选择一个视频。就一个。', ja:'最初の子供を追加して動画を選んでください。たった1本です。', ko:'첫 번째 아이를 추가하고 영상을 선택하세요. 딱 하나만.', hi:'अपना पहला बच्चा जोड़ें और एक वीडियो चुनें। बस एक।', id:'Tambahkan anak pertama Anda dan pilih video. Hanya satu.' },

    /* ── footer ── */
    footerPrivacy: { en:'Privacy Policy', nl:'Privacybeleid', de:'Datenschutz', fr:'Politique de confidentialité', es:'Política de privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'سياسة الخصوصية', zh:'隐私政策', ja:'プライバシーポリシー', ko:'개인정보 처리방침', hi:'गोपनीयता नीति', id:'Kebijakan Privasi' },
    footerTerms:   { en:'Terms of Service', nl:'Gebruiksvoorwaarden', de:'Nutzungsbedingungen', fr:'CGU', es:'Términos de servicio', it:'Termini di servizio', pt:'Termos de serviço', ru:'Условия использования', ar:'شروط الخدمة', zh:'服务条款', ja:'利用規約', ko:'서비스 약관', hi:'सेवा की शर्तें', id:'Syarat Layanan' },

    /* ── FAQ ── */
    faqLabel: { en:'Frequently Asked Questions', nl:'Veelgestelde vragen', de:'Häufig gestellte Fragen', fr:'Questions fréquentes', es:'Preguntas frecuentes', it:'Domande frequenti', pt:'Perguntas frequentes', ru:'Часто задаваемые вопросы', ar:'الأسئلة الشائعة', zh:'常见问题', ja:'よくある質問', ko:'자주 묻는 질문', hi:'अक्सर पूछे जाने वाले प्रश्न', id:'Pertanyaan Umum' },
    faqH2:    { en:'Your questions, answered.', nl:'Jouw vragen, beantwoord.', de:'Ihre Fragen, beantwortet.', fr:'Vos questions, avec réponses.', es:'Tus preguntas, respondidas.', it:'Le tue domande, con risposta.', pt:'Suas perguntas, respondidas.', ru:'Ваши вопросы и ответы.', ar:'أسئلتك مع إجاباتها.', zh:'您的问题，已解答。', ja:'よくある質問と回答。', ko:'자주 묻는 질문과 답변.', hi:'आपके सवाल, उनके जवाब।', id:'Pertanyaan Anda, Terjawab.' },

    faq1Q: { en:'What is PlayOneVideo?', nl:'Wat is PlayOneVideo?', de:'Was ist PlayOneVideo?', fr:'Qu\'est-ce que PlayOneVideo ?', es:'¿Qué es PlayOneVideo?', it:'Cos\'è PlayOneVideo?', pt:'O que é PlayOneVideo?', ru:'Что такое PlayOneVideo?', ar:'ما هو PlayOneVideo؟', zh:'什么是PlayOneVideo？', ja:'PlayOneVideoとは何ですか？', ko:'PlayOneVideo란 무엇인가요?', hi:'PlayOneVideo क्या है?', id:'Apa itu PlayOneVideo?' },
    faq1A: { en:'PlayOneVideo is an iOS app that lets parents choose exactly one YouTube video for their child to watch. When the video ends, the screen goes black. No autoplay, no recommendations, no scrolling — just the one video you chose.', nl:'PlayOneVideo is een iOS-app waarmee ouders precies één YouTube-video kiezen voor hun kind. Als de video afloopt, wordt het scherm zwart. Geen autoplay, geen aanbevelingen, geen scrollen.', de:'PlayOneVideo ist eine iOS-App, mit der Eltern genau ein YouTube-Video für ihr Kind auswählen. Wenn das Video endet, wird der Bildschirm schwarz. Kein Autoplay, keine Empfehlungen, kein Scrollen.', fr:'PlayOneVideo est une application iOS qui permet aux parents de choisir une seule vidéo YouTube pour leur enfant. Quand la vidéo se termine, l\'écran devient noir. Pas de lecture automatique, pas de recommandations, pas de défilement.', es:'PlayOneVideo es una app de iOS que permite a los padres elegir exactamente un vídeo de YouTube para su hijo. Cuando el vídeo termina, la pantalla se pone negra. Sin reproducción automática, sin recomendaciones, sin desplazamiento.', it:'PlayOneVideo è un\'app iOS che permette ai genitori di scegliere un solo video YouTube per il proprio figlio. Quando il video finisce, lo schermo diventa nero. Niente riproduzione automatica, niente consigli, niente scorrimento.', pt:'PlayOneVideo é um app iOS que permite aos pais escolher exatamente um vídeo do YouTube para o filho assistir. Quando o vídeo termina, a tela fica preta. Sem reprodução automática, sem recomendações, sem rolagem.', ru:'PlayOneVideo — iOS-приложение, позволяющее родителям выбрать ровно одно видео на YouTube для ребёнка. Когда видео заканчивается, экран гаснет. Никакого автовоспроизведения, рекомендаций или прокрутки.', ar:'PlayOneVideo تطبيق iOS يتيح للآباء اختيار مقطع يوتيوب واحد لمشاهدة أطفالهم. عند انتهاء المقطع تصبح الشاشة سوداء. لا تشغيل تلقائي، لا توصيات، لا تمرير.', zh:'PlayOneVideo是一款iOS应用，让父母为孩子精确选择一个YouTube视频。视频结束后屏幕变黑。没有自动播放，没有推荐，没有滚动。', ja:'PlayOneVideoは、親が子供のためにYouTube動画を1本だけ選べるiOSアプリです。動画が終わると画面が黒くなります。自動再生なし、おすすめなし、スクロールなし。', ko:'PlayOneVideo는 부모가 자녀를 위해 YouTube 동영상을 정확히 하나만 선택할 수 있는 iOS 앱입니다. 동영상이 끝나면 화면이 검게 변합니다. 자동 재생 없음, 추천 없음, 스크롤 없음.', hi:'PlayOneVideo एक iOS ऐप है जो माता-पिता को अपने बच्चे के लिए ठीक एक YouTube वीडियो चुनने देता है। वीडियो समाप्त होने पर स्क्रीन काली हो जाती है। कोई ऑटोप्ले नहीं, कोई सुझाव नहीं, कोई स्क्रॉलिंग नहीं।', id:'PlayOneVideo adalah aplikasi iOS yang memungkinkan orang tua memilih tepat satu video YouTube untuk ditonton anak. Saat video berakhir, layar menjadi hitam. Tanpa putar otomatis, tanpa rekomendasi, tanpa scrolling.' },

    faq2Q: { en:'Is this better than YouTube Kids?', nl:'Is dit beter dan YouTube Kids?', de:'Ist das besser als YouTube Kids?', fr:'Est-ce mieux que YouTube Kids ?', es:'¿Es mejor que YouTube Kids?', it:'È meglio di YouTube Kids?', pt:'É melhor que o YouTube Kids?', ru:'Лучше ли это, чем YouTube Kids?', ar:'هل هذا أفضل من YouTube Kids؟', zh:'这比YouTube Kids更好吗？', ja:'YouTube Kidsより良いですか？', ko:'YouTube Kids보다 더 좋은가요?', hi:'क्या यह YouTube Kids से बेहतर है?', id:'Apakah lebih baik dari YouTube Kids?' },
    faq2A: { en:'YouTube Kids still shows endless suggestions and autoplay. PlayOneVideo gives you complete control — you pick the video, the child watches it, the screen turns off. No feed, no recommendations, no way to click to something else.', nl:'YouTube Kids toont nog steeds eindeloze suggesties en autoplay. PlayOneVideo geeft je volledige controle: jij kiest de video, het kind kijkt, het scherm gaat uit. Geen feed, geen aanbevelingen, geen manier om door te klikken.', de:'YouTube Kids zeigt immer noch endlose Vorschläge und Autoplay. PlayOneVideo gibt dir die vollständige Kontrolle: Du wählst das Video, das Kind schaut, der Bildschirm geht aus. Kein Feed, keine Empfehlungen, kein Weiterklicken.', fr:'YouTube Kids montre encore des suggestions infinies et la lecture automatique. PlayOneVideo vous donne un contrôle total : vous choisissez la vidéo, l\'enfant la regarde, l\'écran s\'éteint. Aucun fil, aucune recommandation, impossible de cliquer ailleurs.', es:'YouTube Kids sigue mostrando sugerencias infinitas y reproducción automática. PlayOneVideo te da control total: tú eliges el vídeo, el niño lo ve, la pantalla se apaga. Sin feed, sin recomendaciones, sin posibilidad de hacer clic en otra cosa.', it:'YouTube Kids mostra ancora suggerimenti infiniti e riproduzione automatica. PlayOneVideo ti dà il controllo completo: scegli il video, il bambino lo guarda, lo schermo si spegne. Nessun feed, nessun consiglio, impossibile cliccare su altro.', pt:'O YouTube Kids ainda mostra sugestões infinitas e reprodução automática. PlayOneVideo dá controle total: você escolhe o vídeo, o filho assiste, a tela apaga. Sem feed, sem recomendações, sem como clicar em outra coisa.', ru:'YouTube Kids по-прежнему показывает бесконечные рекомендации и автовоспроизведение. PlayOneVideo даёт полный контроль: вы выбираете видео, ребёнок смотрит, экран гаснет. Никакой ленты, рекомендаций или возможности перейти на другое.', ar:'YouTube Kids لا يزال يعرض اقتراحات لا نهائية وتشغيلاً تلقائياً. يمنحك PlayOneVideo السيطرة الكاملة: أنت تختار المقطع، يشاهده الطفل، تنطفئ الشاشة. لا خلاصة، لا توصيات، لا طريقة للنقر على شيء آخر.', zh:'YouTube Kids仍然显示无尽的建议和自动播放。PlayOneVideo给你完全控制权：你选择视频，孩子观看，屏幕关闭。没有信息流，没有推荐，没有办法点击其他内容。', ja:'YouTube Kidsはまだ無限のおすすめと自動再生を表示します。PlayOneVideoは完全なコントロールを提供します：あなたが動画を選び、子供が視聴し、画面が消えます。フィードなし、おすすめなし、他のものをクリックできません。', ko:'YouTube Kids는 여전히 무한한 추천과 자동 재생을 보여줍니다. PlayOneVideo는 완전한 제어권을 줍니다: 부모가 동영상을 선택하고, 아이가 시청하고, 화면이 꺼집니다. 피드 없음, 추천 없음, 다른 것을 클릭할 방법 없음.', hi:'YouTube Kids अभी भी अंतहीन सुझाव और ऑटोप्ले दिखाता है। PlayOneVideo आपको पूरा नियंत्रण देता है: आप वीडियो चुनते हैं, बच्चा देखता है, स्क्रीन बंद हो जाती है। कोई फ़ीड नहीं, कोई सुझाव नहीं, कुछ और क्लिक करने का कोई तरीका नहीं।', id:'YouTube Kids masih menampilkan saran tanpa henti dan putar otomatis. PlayOneVideo memberi Anda kontrol penuh: Anda memilih video, anak menontonnya, layar mati. Tidak ada feed, tidak ada rekomendasi, tidak ada cara untuk mengklik hal lain.' },

    faq3Q: { en:'How much does PlayOneVideo cost?', nl:'Wat kost PlayOneVideo?', de:'Was kostet PlayOneVideo?', fr:'Combien coûte PlayOneVideo ?', es:'¿Cuánto cuesta PlayOneVideo?', it:'Quanto costa PlayOneVideo?', pt:'Quanto custa o PlayOneVideo?', ru:'Сколько стоит PlayOneVideo?', ar:'كم تكلفة PlayOneVideo؟', zh:'PlayOneVideo多少钱？', ja:'PlayOneVideoはいくらですか？', ko:'PlayOneVideo는 얼마인가요?', hi:'PlayOneVideo की कीमत क्या है?', id:'Berapa biaya PlayOneVideo?' },
    faq3A: { en:'PlayOneVideo starts with a 14-day free trial, then €1.99 per month. One subscription covers your whole family — your partner gets access too, at no extra charge.', nl:'PlayOneVideo begint met 14 dagen gratis, daarna €1,99 per maand. Eén abonnement dekt je hele gezin: je partner heeft ook toegang, zonder extra kosten.', de:'PlayOneVideo beginnt mit 14 Tagen kostenlos, danach 1,99 € pro Monat. Ein Abonnement deckt die ganze Familie ab – dein Partner hat auch Zugang, ohne Aufpreis.', fr:'PlayOneVideo commence par 14 jours d\'essai gratuit, puis 1,99 €/mois. Un abonnement couvre toute la famille — votre partenaire y a aussi accès sans supplément.', es:'PlayOneVideo comienza con 14 días de prueba gratis, luego €1,99 al mes. Una suscripción cubre a toda la familia: tu pareja también tiene acceso sin coste adicional.', it:'PlayOneVideo inizia con 14 giorni gratuiti, poi €1,99 al mese. Un abbonamento copre tutta la famiglia: anche il tuo partner ha accesso senza costi aggiuntivi.', pt:'PlayOneVideo começa com 14 dias grátis, depois €1,99 por mês. Uma assinatura cobre toda a família — seu parceiro também tem acesso sem custo extra.', ru:'PlayOneVideo начинается с 14 дней бесплатно, затем 1,99 € в месяц. Одна подписка покрывает всю семью — партнёр тоже получает доступ без доплаты.', ar:'يبدأ PlayOneVideo بتجربة مجانية 14 يوماً، ثم 1.99 يورو شهرياً. اشتراك واحد يغطي عائلتك بالكامل — شريكك أيضاً يحصل على وصول دون رسوم إضافية.', zh:'PlayOneVideo从14天免费试用开始，之后每月€1.99。一个订阅覆盖整个家庭，伴侣也可使用，无需额外费用。', ja:'PlayOneVideoは14日間無料トライアルから始まり、その後月額€1.99です。1つのサブスクリプションで家族全員をカバー。パートナーも追加料金なしでアクセスできます。', ko:'PlayOneVideo는 14일 무료 체험으로 시작하고, 이후 월 €1.99입니다. 구독 하나로 온 가족 커버 — 파트너도 추가 비용 없이 이용 가능합니다.', hi:'PlayOneVideo 14 दिन के मुफ्त ट्रायल से शुरू होता है, फिर प्रति माह €1.99। एक सब्सक्रिप्शन पूरे परिवार को कवर करती है — पार्टनर को भी बिना अतिरिक्त शुल्क के एक्सेस।', id:'PlayOneVideo dimulai dengan uji coba gratis 14 hari, lalu €1,99 per bulan. Satu langganan mencakup seluruh keluarga — pasangan juga mendapat akses tanpa biaya tambahan.' },

    faq4Q: { en:'Does PlayOneVideo collect data about my child?', nl:'Verzamelt PlayOneVideo gegevens over mijn kind?', de:'Sammelt PlayOneVideo Daten über mein Kind?', fr:'PlayOneVideo collecte-t-il des données sur mon enfant ?', es:'¿PlayOneVideo recopila datos sobre mi hijo?', it:'PlayOneVideo raccoglie dati su mio figlio?', pt:'O PlayOneVideo coleta dados sobre meu filho?', ru:'Собирает ли PlayOneVideo данные о моём ребёнке?', ar:'هل يجمع PlayOneVideo بيانات عن طفلي؟', zh:'PlayOneVideo会收集我孩子的数据吗？', ja:'PlayOneVideoは子供のデータを収集しますか？', ko:'PlayOneVideo가 내 아이에 대한 데이터를 수집하나요?', hi:'क्या PlayOneVideo मेरे बच्चे के बारे में डेटा एकत्र करता है?', id:'Apakah PlayOneVideo mengumpulkan data tentang anak saya?' },
    faq4A: { en:'No. PlayOneVideo only stores a user ID, a nickname for your child, and their saved video list. No personal data, no behavioral tracking, no ads.', nl:'Nee. PlayOneVideo slaat alleen een gebruikers-ID, een bijnaam voor je kind en hun videolijst op. Geen persoonsgegevens, geen gedragsregistratie, geen reclame.', de:'Nein. PlayOneVideo speichert nur eine Benutzer-ID, einen Spitznamen für dein Kind und ihre Videoliste. Keine persönlichen Daten, kein Verhaltens-Tracking, keine Werbung.', fr:'Non. PlayOneVideo ne stocke qu\'un identifiant utilisateur, un surnom pour votre enfant et leur liste de vidéos. Aucune donnée personnelle, aucun suivi comportemental, aucune publicité.', es:'No. PlayOneVideo solo almacena un ID de usuario, un apodo para tu hijo y su lista de vídeos. Sin datos personales, sin seguimiento del comportamiento, sin anuncios.', it:'No. PlayOneVideo memorizza solo un ID utente, un soprannome per il bambino e la loro lista di video. Nessun dato personale, nessun tracciamento, nessuna pubblicità.', pt:'Não. PlayOneVideo armazena apenas um ID de usuário, um apelido para seu filho e a lista de vídeos. Sem dados pessoais, sem rastreamento comportamental, sem anúncios.', ru:'Нет. PlayOneVideo хранит только идентификатор пользователя, псевдоним ребёнка и список сохранённых видео. Никаких личных данных, поведенческого отслеживания или рекламы.', ar:'لا. يخزن PlayOneVideo فقط معرف المستخدم ولقب طفلك وقائمة مقاطعهم. لا بيانات شخصية، لا تتبع سلوكي، لا إعلانات.', zh:'不会。PlayOneVideo只存储用户ID、孩子的昵称和视频列表。没有个人数据，没有行为追踪，没有广告。', ja:'いいえ。PlayOneVideoはユーザーID、子供のニックネーム、保存した動画リストのみを保存します。個人データなし、行動追跡なし、広告なし。', ko:'아니요. PlayOneVideo는 사용자 ID, 아이의 닉네임, 저장된 동영상 목록만 저장합니다. 개인 데이터 없음, 행동 추적 없음, 광고 없음.', hi:'नहीं। PlayOneVideo केवल एक उपयोगकर्ता ID, बच्चे का उपनाम और वीडियो सूची संग्रहीत करता है। कोई व्यक्तिगत डेटा नहीं, कोई ट्रैकिंग नहीं, कोई विज्ञापन नहीं।', id:'Tidak. PlayOneVideo hanya menyimpan ID pengguna, nama panggilan anak, dan daftar video tersimpan. Tidak ada data pribadi, tidak ada pelacakan, tidak ada iklan.' },

    faq5Q: { en:'Which phones does it work on?', nl:'Op welke telefoons werkt het?', de:'Auf welchen Geräten funktioniert es?', fr:'Sur quels appareils fonctionne-t-il ?', es:'¿En qué dispositivos funciona?', it:'Su quali dispositivi funziona?', pt:'Em quais dispositivos funciona?', ru:'На каких устройствах работает?', ar:'على أي أجهزة يعمل؟', zh:'在哪些设备上可以使用？', ja:'どの端末で使えますか？', ko:'어떤 기기에서 사용할 수 있나요?', hi:'यह किन डिवाइस पर काम करता है?', id:'Di perangkat apa saja ini bekerja?' },
    faq5A: { en:'PlayOneVideo is currently available on iPhone and iPad (iOS). An Android version is in development and coming soon.', nl:'PlayOneVideo is momenteel beschikbaar op iPhone en iPad (iOS). Een Android-versie is in ontwikkeling en komt binnenkort.', de:'PlayOneVideo ist derzeit für iPhone und iPad (iOS) verfügbar. Eine Android-Version ist in Entwicklung und kommt bald.', fr:'PlayOneVideo est actuellement disponible sur iPhone et iPad (iOS). Une version Android est en cours de développement et arrive bientôt.', es:'PlayOneVideo está disponible actualmente en iPhone y iPad (iOS). Una versión para Android está en desarrollo y llegará pronto.', it:'PlayOneVideo è attualmente disponibile su iPhone e iPad (iOS). Una versione Android è in sviluppo e arriverà presto.', pt:'PlayOneVideo está disponível atualmente no iPhone e iPad (iOS). Uma versão para Android está em desenvolvimento e chegará em breve.', ru:'PlayOneVideo сейчас доступен на iPhone и iPad (iOS). Версия для Android находится в разработке и скоро появится.', ar:'PlayOneVideo متاح حالياً على iPhone وiPad (iOS). نسخة Android قيد التطوير وستصدر قريباً.', zh:'PlayOneVideo目前适用于iPhone和iPad（iOS）。Android版本正在开发中，即将推出。', ja:'PlayOneVideoは現在iPhone・iPad（iOS）でご利用いただけます。Android版は開発中で、近日公開予定です。', ko:'PlayOneVideo는 현재 iPhone과 iPad(iOS)에서 이용 가능합니다. Android 버전은 개발 중이며 곧 출시됩니다.', hi:'PlayOneVideo अभी iPhone और iPad (iOS) पर उपलब्ध है। Android वर्शन विकास में है और जल्द आ रहा है।', id:'PlayOneVideo saat ini tersedia di iPhone dan iPad (iOS). Versi Android sedang dikembangkan dan akan segera hadir.' },
  };

  function getLang() {
    const saved = localStorage.getItem('pov_lang');
    if (saved && T.navAffiliate[saved]) return saved;
    const browser = (navigator.language || 'en').substring(0, 2).toLowerCase();
    return T.navAffiliate[browser] ? browser : 'en';
  }

  function applyLang(lang) {
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (T[key] && T[key][lang] !== undefined) {
        el.textContent = T[key][lang];
      }
    });
    // Update select
    const sel = document.getElementById('lang-select');
    if (sel) sel.value = lang;
  }

  function buildSelector() {
    const sel = document.createElement('select');
    sel.id = 'lang-select';
    sel.style.cssText = 'background:transparent;border:none;font-size:13px;font-weight:500;color:var(--muted);cursor:pointer;font-family:inherit;padding:2px 4px;border-radius:4px;';
    sel.title = 'Language';
    Object.entries(LANGS).forEach(([code, name]) => {
      const opt = document.createElement('option');
      opt.value = code;
      opt.textContent = name;
      sel.appendChild(opt);
    });
    sel.value = getLang();
    sel.addEventListener('change', () => {
      localStorage.setItem('pov_lang', sel.value);
      applyLang(sel.value);
    });
    return sel;
  }

  document.addEventListener('DOMContentLoaded', () => {
    const navLinks = document.querySelector('.nav-links');
    if (navLinks) {
      const li = document.createElement('li');
      li.appendChild(buildSelector());
      navLinks.appendChild(li);
    }
    applyLang(getLang());
  });
})();
