/* PlayOneVideo — website i18n */
(function () {
  const LANGS = {
    en: 'English', nl: 'Nederlands', de: 'Deutsch', fr: 'Français',
    es: 'Español', it: 'Italiano', pt: 'Português', ru: 'Русский',
    ar: 'العربية', zh: '中文', ja: '日本語', ko: '한국어',
    hi: 'हिन्दी', id: 'Bahasa Indonesia',
  };

  const T = {
    /* ── nav ── */
    navAffiliate: { en:'Affiliate', nl:'Word affiliate', de:'Affiliate', fr:'Affilié', es:'Afiliado', it:'Affiliato', pt:'Afiliado', ru:'Партнёрство', ar:'شراكة', zh:'推广合作', ja:'アフィリエイト', ko:'제휴', hi:'सहयोगी', id:'Afiliasi' },
    navPrivacy:   { en:'Privacy', nl:'Privacy', de:'Datenschutz', fr:'Confidentialité', es:'Privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'الخصوصية', zh:'隐私', ja:'プライバシー', ko:'개인정보', hi:'गोपनीयता', id:'Privasi' },
    navTerms:     { en:'Terms', nl:'Voorwaarden', de:'AGB', fr:'CGU', es:'Términos', it:'Termini', pt:'Termos', ru:'Условия', ar:'الشروط', zh:'条款', ja:'利用規約', ko:'이용약관', hi:'शर्तें', id:'Syarat' },

    /* ── hero ── */
    heroH1:    { en:'Let kids watch one video.', nl:'Laat kinderen één filmpje kijken.', de:'Lass Kinder ein Video ansehen.', fr:'Laissez les enfants regarder une vidéo.', es:'Deja que los niños vean un vídeo.', it:'Lascia che i bambini guardino un video.', pt:'Deixe as crianças assistir um vídeo.', ru:'Позвольте ребёнку посмотреть одно видео.', ar:'دع الأطفال يشاهدون مقطعاً واحداً.', zh:'让孩子看一个视频。', ja:'子供に動画を1本見せよう。', ko:'아이가 영상 하나를 보게 하세요.', hi:'बच्चों को एक वीडियो देखने दें।', id:'Biarkan anak menonton satu video.' },
    heroSub:   { en:'Use YouTube in a child-friendly way.\n\nNo suggestions.\nNo clicking through.\nNo arguments.', nl:'Gebruik YouTube op een kindvriendelijke manier.\n\nGeen suggesties.\nNiet doorklikken.\nGeen ruzie.', de:'Nutze YouTube auf eine kindergerechte Weise.\n\nKeine Vorschläge.\nKein Weiterklicken.\nKein Streit.', fr:'Utilisez YouTube de façon adaptée aux enfants.\n\nPas de suggestions.\nPas de navigation aléatoire.\nPas de disputes.', es:'Usa YouTube de forma adaptada a los niños.\n\nSin sugerencias.\nSin hacer clic en otros.\nSin discusiones.', it:'Usa YouTube in modo adatto ai bambini.\n\nNiente suggerimenti.\nNiente clic su altri video.\nNiente litigi.', pt:'Use o YouTube de forma adequada para crianças.\n\nSem sugestões.\nSem clicar em outros.\nSem brigas.', ru:'Используйте YouTube безопасно для детей.\n\nНикаких рекомендаций.\nНикаких переходов.\nНикаких споров.', ar:'استخدم YouTube بطريقة مناسبة للأطفال.\n\nلا اقتراحات.\nلا نقر على مقاطع أخرى.\nلا جدالات.', zh:'以儿童友好的方式使用YouTube。\n\n没有推荐。\n不乱点击。\n没有争吵。', ja:'子供に安全なYouTubeの使い方。\n\nおすすめなし。\n他の動画へのクリックなし。\n言い争いなし。', ko:'아이에게 안전한 YouTube 사용법。\n\n추천 없음。\n다른 영상 클릭 없음。\n다툼 없음。', hi:'बच्चों के लिए YouTube का सुरक्षित उपयोग।\n\nकोई सुझाव नहीं।\nआगे क्लिक नहीं।\nकोई झगड़ा नहीं।', id:'Gunakan YouTube dengan cara yang ramah anak.\n\nTanpa saran.\nTanpa klik video lain.\nTanpa pertengkaran.' },
    heroPrice: { en:'14 days free, then $1.99 per month. Cancel anytime.', nl:'14 dagen gratis, daarna €1,99 per maand. Opzegbaar wanneer je wilt.', de:'14 Tage kostenlos, dann €1,99 pro Monat. Jederzeit kündbar.', fr:'14 jours gratuits, puis 1,99 €/mois. Annulable à tout moment.', es:'14 días gratis, luego €1,99/mes. Cancela cuando quieras.', it:'14 giorni gratis, poi €1,99/mese. Disdici quando vuoi.', pt:'14 dias grátis, depois R$10,90/mês. Cancele quando quiser.', ru:'14 дней бесплатно, затем 199 ₽ в месяц. Отмена в любое время.', ar:'14 يوماً مجاناً، ثم 7.99 ر.س شهرياً. إلغاء في أي وقت.', zh:'免费14天，之后每月¥18。随时可取消。', ja:'14日間無料、その後月¥300。いつでもキャンセル可。', ko:'14일 무료, 이후 월 ₩3,300. 언제든지 취소 가능.', hi:'14 दिन मुफ्त, फिर ₹160/माह। कभी भी रद्द करें।', id:'14 hari gratis, lalu Rp32.000/bulan. Batalkan kapan saja.' },
    heroComingSoon: { en:'coming soon', nl:'binnenkort', de:'bald verfügbar', fr:'bientôt', es:'próximamente', it:'presto', pt:'em breve', ru:'скоро', ar:'قريباً', zh:'即将推出', ja:'近日公開', ko:'곧 출시', hi:'जल्द आ रहा है', id:'segera hadir' },

    /* ── problem section ── */
    problemLabel: { en:'The problem', nl:'Het probleem', de:'Das Problem', fr:'Le problème', es:'El problema', it:'Il problema', pt:'O problema', ru:'Проблема', ar:'المشكلة', zh:'问题', ja:'問題', ko:'문제', hi:'समस्या', id:'Masalah' },
    problemH2:    { en:'Sound familiar?', nl:'Ken je dit?', de:'Kennt ihr das?', fr:'Ça vous parle ?', es:'¿Te suena?', it:'Ti suona familiare?', pt:'Familiar?', ru:'Узнаёте?', ar:'هل هذا مألوف؟', zh:'听起来熟悉吗？', ja:'よくある話では？', ko:'익숙한 상황인가요?', hi:'पहचाना?', id:'Familiar?' },
    problemBody:  { en:'Your child is allowed to watch 1 video.', nl:'Je kind mag 1 filmpje kijken.', de:'Dein Kind darf 1 Video ansehen.', fr:'Votre enfant a le droit de regarder 1 vidéo.', es:'Tu hijo puede ver 1 vídeo.', it:'Tuo figlio può guardare 1 video.', pt:'Seu filho pode assistir 1 vídeo.', ru:'Ребёнку можно посмотреть 1 видео.', ar:'يُسمح لطفلك بمشاهدة مقطع واحد.', zh:'孩子只能看1个视频。', ja:'子供が見ていいのはビデオ1本だけ。', ko:'아이가 영상 1개만 볼 수 있는데.', hi:'बच्चे को 1 वीडियो देखने की अनुमति है।', id:'Anak Anda boleh menonton 1 video.' },
    calloutLine1: { en:'Scrolls around.', nl:'Scrollt door.', de:'Scrollt weiter.', fr:'Il fait défiler.', es:'Se pone a hacer scroll.', it:'Scorre avanti.', pt:'Fica rolando.', ru:'Листает.', ar:'يتصفّح.', zh:'开始滑屏。', ja:'スクロールしはじめる。', ko:'스크롤하다가.', hi:'स्क्रॉल करता है।', id:'Malah scroll.' },
    calloutLine2: { en:'Clicks away.', nl:'Klikt door.', de:'Klickt weiter.', fr:'Clique sur autre chose.', es:'Hace clic en todo.', it:'Clicca ovunque.', pt:'Fica clicando.', ru:'Кликает дальше.', ar:'ينقر ويتنقّل.', zh:'乱点视频。', ja:'クリックしてしまう。', ko:'이것저것 클릭.', hi:'क्लिक करता है।', id:'Klik sana-sini.' },
    calloutLine3: { en:'Arguments.', nl:'Ruzie.', de:'Streit.', fr:'Disputes.', es:'Discusiones.', it:'Litigi.', pt:'Briga.', ru:'Скандал.', ar:'شجار.', zh:'争吵。', ja:'言い争い。', ko:'다툼.', hi:'झगड़ा।', id:'Bertengkar.' },

    /* ── approach section ── */
    approachLabel: { en:'Our approach', nl:'Onze aanpak', de:'Unser Ansatz', fr:'Notre approche', es:'Nuestro enfoque', it:'Il nostro approccio', pt:'Nossa abordagem', ru:'Наш подход', ar:'مقاربتنا', zh:'我们的方法', ja:'私たちのアプローチ', ko:'우리의 접근법', hi:'हमारा दृष्टिकोण', id:'Pendekatan kami' },
    approachH2:    { en:'All video apps make kids addicted.', nl:'Alle videoapps maken kinderen verslaafd.', de:'Alle Video-Apps machen Kinder süchtig.', fr:'Toutes les applis vidéo rendent les enfants accros.', es:'Todas las apps de vídeo enganchan a los niños.', it:'Tutte le app video creano dipendenza nei bambini.', pt:'Todos os apps de vídeo viciam as crianças.', ru:'Все видеоприложения вызывают зависимость у детей.', ar:'كل تطبيقات الفيديو تُدمن الأطفال.', zh:'所有视频应用都让孩子上瘾。', ja:'すべての動画アプリが子供を依存させる。', ko:'모든 동영상 앱이 아이를 중독시킵니다.', hi:'सभी वीडियो ऐप्स बच्चों को लत लगा देते हैं।', id:'Semua aplikasi video membuat anak kecanduan.' },
    approachBody:  { en:'This app is intentionally boring. It plays one video.', nl:'Deze app is expres saai. Hij speelt één video af.', de:'Diese App ist absichtlich langweilig. Sie spielt ein Video ab.', fr:'Cette appli est volontairement ennuyeuse. Elle joue une seule vidéo.', es:'Esta app es aburrida a propósito. Reproduce un vídeo.', it:'Questa app è volutamente noiosa. Riproduce un solo video.', pt:'Este app é propositalmente chato. Ele toca um vídeo.', ru:'Это приложение намеренно скучное. Оно воспроизводит одно видео.', ar:'هذا التطبيق مُصمَّم ليكون مملاً. يشغّل مقطعاً واحداً فقط.', zh:'这款应用故意设计得无聊。它只播放一个视频。', ja:'このアプリは意図的につまらなく作られています。動画を1本再生するだけです。', ko:'이 앱은 의도적으로 지루하게 만들었습니다. 영상 하나만 재생합니다.', hi:'यह ऐप जानबूझकर नीरस है। यह एक वीडियो चलाता है।', id:'Aplikasi ini sengaja dibuat membosankan. Ia memutar satu video.' },
    feat1Title: { en:'No bright colours', nl:'Geen felle kleuren', de:'Keine grellen Farben', fr:'Pas de couleurs vives', es:'Sin colores llamativos', it:'Nessun colore sgargiante', pt:'Sem cores vivas', ru:'Никаких ярких цветов', ar:'لا ألوان صارخة', zh:'无鲜艳颜色', ja:'派手な色なし', ko:'밝은 색상 없음', hi:'चमकीले रंग नहीं', id:'Tidak ada warna cerah' },
    feat1Body: { en:'Calm interface. Attention on the video, not the app.', nl:'Rustige interface. Aandacht bij het filmpje, niet bij de app.', de:'Ruhige Oberfläche. Aufmerksamkeit auf das Video, nicht auf die App.', fr:'Interface apaisante. Attention sur la vidéo, pas sur l\'appli.', es:'Interfaz tranquila. Atención en el vídeo, no en la app.', it:'Interfaccia tranquilla. Attenzione al video, non all\'app.', pt:'Interface calma. Atenção no vídeo, não no app.', ru:'Спокойный интерфейс. Внимание на видео, а не на приложении.', ar:'واجهة هادئة. التركيز على الفيديو، لا على التطبيق.', zh:'平静的界面。注意力放在视频上，而非应用。', ja:'落ち着いたインターフェース。注意はアプリではなく動画へ。', ko:'차분한 인터페이스. 앱이 아닌 영상에 집중.', hi:'शांत इंटरफेस। ध्यान वीडियो पर, ऐप पर नहीं।', id:'Antarmuka tenang. Perhatian pada video, bukan aplikasi.' },
    feat2Title: { en:'No animations', nl:'Geen animaties', de:'Keine Animationen', fr:'Pas d\'animations', es:'Sin animaciones', it:'Nessuna animazione', pt:'Sem animações', ru:'Никакой анимации', ar:'لا رسوم متحركة', zh:'无动画', ja:'アニメーションなし', ko:'애니메이션 없음', hi:'कोई एनिमेशन नहीं', id:'Tidak ada animasi' },
    feat2Body: { en:'Nothing that stimulates or distracts.', nl:'Niets dat prikkelt of afleidt.', de:'Nichts, das stimuliert oder ablenkt.', fr:'Rien qui stimule ou distrait.', es:'Nada que estimule o distraiga.', it:'Niente che stimoli o distragga.', pt:'Nada que estimule ou distraia.', ru:'Ничего, что стимулирует или отвлекает.', ar:'لا شيء يُحفّز أو يُشتّت.', zh:'没有任何刺激或分散注意力的东西。', ja:'刺激したり気を散らすものは何もない。', ko:'자극하거나 산만하게 만드는 것 없음.', hi:'कोई उत्तेजना या विकर्षण नहीं।', id:'Tidak ada yang merangsang atau mengalihkan perhatian.' },
    feat3Title: { en:'No scores or rewards', nl:'Geen scores of beloningen', de:'Keine Punkte oder Belohnungen', fr:'Pas de scores ni de récompenses', es:'Sin puntuaciones ni recompensas', it:'Nessun punteggio o premio', pt:'Sem pontuações ou recompensas', ru:'Никаких очков или наград', ar:'لا نقاط ولا مكافآت', zh:'无得分或奖励', ja:'得点も報酬もなし', ko:'점수나 보상 없음', hi:'कोई स्कोर या पुरस्कार नहीं', id:'Tidak ada skor atau hadiah' },
    feat3Body: { en:'No likes, streaks or points to come back for.', nl:'Geen likes, streaks of punten om op terug te komen.', de:'Keine Likes, Streaks oder Punkte, die zum Wiederkommen verleiten.', fr:'Pas de likes, séries ou points pour revenir.', es:'Sin me gusta, rachas ni puntos para volver.', it:'Nessun like, serie o punto per tornare.', pt:'Sem curtidas, sequências ou pontos para voltar.', ru:'Никаких лайков, серий или очков, ради которых хочется вернуться.', ar:'لا إعجابات ولا سلاسل ولا نقاط تجعلك تعود.', zh:'没有点赞、连续天数或积分让你回来。', ja:'戻ってくる理由となるいいね！、ストリーク、ポイントなし。', ko:'다시 오게 만드는 좋아요, 연속 기록, 포인트 없음.', hi:'वापस आने के लिए कोई लाइक, स्ट्रीक या पॉइंट नहीं।', id:'Tidak ada suka, streak, atau poin untuk kembali.' },
    feat4Title: { en:'Intentionally boring', nl:'Expres saai', de:'Absichtlich langweilig', fr:'Volontairement ennuyeux', es:'Aburrida a propósito', it:'Volutamente noioso', pt:'Propositalmente chato', ru:'Намеренно скучное', ar:'مملّ عمداً', zh:'故意无聊', ja:'意図的につまらない', ko:'의도적으로 지루한', hi:'जानबूझकर नीरस', id:'Sengaja membosankan' },
    feat4Body: { en:'Designed to be as little addictive as possible.', nl:'Ontworpen om zo min mogelijk verslavend te zijn.', de:'Entworfen, um so wenig wie möglich süchtig zu machen.', fr:'Conçu pour être le moins addictif possible.', es:'Diseñada para ser lo menos adictiva posible.', it:'Progettato per essere il meno possibile dipendente.', pt:'Projetado para ser o menos viciante possível.', ru:'Разработано так, чтобы вызывать как можно меньше зависимости.', ar:'مُصمَّم ليكون أقل إدماناً ممكناً.', zh:'设计上尽可能减少成瘾性。', ja:'できる限り依存性が少なくなるよう設計されています。', ko:'최대한 중독성이 없도록 설계되었습니다.', hi:'यथासंभव कम नशे की लत के लिए डिज़ाइन किया गया।', id:'Dirancang untuk sesedikit mungkin membuat kecanduan.' },

    /* ── how it works ── */
    howLabel: { en:'How it works', nl:'Hoe het werkt', de:'So funktioniert\'s', fr:'Comment ça marche', es:'Cómo funciona', it:'Come funziona', pt:'Como funciona', ru:'Как это работает', ar:'كيف يعمل', zh:'如何运作', ja:'使い方', ko:'작동 방식', hi:'यह कैसे काम करता है', id:'Cara kerjanya' },
    howH2:    { en:'It\'s that simple.', nl:'Zo simpel is het.', de:'So einfach ist das.', fr:'C\'est aussi simple que ça.', es:'Así de sencillo.', it:'È così semplice.', pt:'É simples assim.', ru:'Всё просто.', ar:'الأمر بهذه البساطة.', zh:'就是这么简单。', ja:'それだけシンプル。', ko:'이렇게 간단합니다.', hi:'बस इतना ही सरल।', id:'Sesederhana itu.' },
    step1: { en:'Select a video', nl:'Klik een filmpje aan', de:'Video auswählen', fr:'Choisir une vidéo', es:'Elige un vídeo', it:'Seleziona un video', pt:'Escolha um vídeo', ru:'Выберите видео', ar:'اختر مقطعاً', zh:'选择一个视频', ja:'動画を選ぶ', ko:'영상 선택', hi:'एक वीडियो चुनें', id:'Pilih video' },
    step2: { en:'Child watches calmly', nl:'Kind kijkt rustig', de:'Kind schaut ruhig', fr:'L\'enfant regarde tranquillement', es:'El niño mira tranquilo', it:'Il bambino guarda tranquillo', pt:'A criança assiste calmamente', ru:'Ребёнок спокойно смотрит', ar:'يشاهد الطفل بهدوء', zh:'孩子安静地观看', ja:'子供が落ち着いて見る', ko:'아이가 조용히 시청', hi:'बच्चा शांति से देखता है', id:'Anak menonton dengan tenang' },
    step3: { en:'Screen goes black', nl:'Scherm wordt zwart', de:'Bildschirm wird schwarz', fr:'L\'écran devient noir', es:'La pantalla se vuelve negra', it:'Lo schermo diventa nero', pt:'A tela fica preta', ru:'Экран гаснет', ar:'تسودّ الشاشة', zh:'屏幕变黑', ja:'画面が暗くなる', ko:'화면이 꺼짐', hi:'स्क्रीन काली हो जाती है', id:'Layar menjadi hitam' },

    /* ── design section ── */
    designLabel: { en:'Design', nl:'Ontwerp', de:'Design', fr:'Design', es:'Diseño', it:'Design', pt:'Design', ru:'Дизайн', ar:'التصميم', zh:'设计', ja:'デザイン', ko:'디자인', hi:'डिज़ाइन', id:'Desain' },
    designH2:   { en:'Intentionally boring.', nl:'Expres saai.', de:'Absichtlich langweilig.', fr:'Volontairement ennuyeux.', es:'Aburrida a propósito.', it:'Volutamente noioso.', pt:'Propositalmente chato.', ru:'Намеренно скучное.', ar:'مملّ عمداً.', zh:'故意无聊。', ja:'意図的につまらない。', ko:'의도적으로 지루한.', hi:'जानबूझकर नीरस।', id:'Sengaja membosankan.' },
    designBody: { en:'No bright colours. No animations. No scores or rewards.\n\nThe interface does not stimulate, so attention stays on the video and not on the app. The app is designed to be as little addictive as possible.', nl:'Geen felle kleuren. Geen animaties. Geen scores of beloningen.\n\nDe interface prikkelt niet, zodat de aandacht bij het filmpje blijft en niet bij de app. De app is ontworpen om zo min mogelijk verslavend te zijn.', de:'Keine grellen Farben. Keine Animationen. Keine Punkte oder Belohnungen.\n\nDie Oberfläche stimuliert nicht, sodass die Aufmerksamkeit beim Video bleibt und nicht bei der App.', fr:'Pas de couleurs vives. Pas d\'animations. Pas de scores ni de récompenses.\n\nL\'interface ne stimule pas, l\'attention reste sur la vidéo et non sur l\'appli.', es:'Sin colores llamativos. Sin animaciones. Sin puntuaciones ni recompensas.\n\nLa interfaz no estimula, la atención se queda en el vídeo.', it:'Nessun colore sgargiante. Nessuna animazione. Nessun punteggio o premio.\n\nL\'interfaccia non stimola, l\'attenzione rimane sul video.', pt:'Sem cores vivas. Sem animações. Sem pontuações ou recompensas.\n\nA interface não estimula, a atenção fica no vídeo.', ru:'Никаких ярких цветов. Никакой анимации. Никаких очков или наград.\n\nИнтерфейс не стимулирует, поэтому внимание остаётся на видео.', ar:'لا ألوان صارخة. لا رسوم متحركة. لا نقاط ولا مكافآت.\n\nالواجهة لا تُحفّز، لذا يبقى التركيز على الفيديو.', zh:'无鲜艳颜色。无动画。无得分或奖励。\n\n界面不会刺激感官，注意力保持在视频上。', ja:'派手な色なし。アニメーションなし。得点も報酬もなし。\n\nインターフェースは刺激しないため、注意が動画に向けられます。', ko:'밝은 색상 없음. 애니메이션 없음. 점수나 보상 없음.\n\n인터페이스가 자극하지 않아 주의가 영상에 집중됩니다.', hi:'कोई चमकीले रंग नहीं। कोई एनिमेशन नहीं। कोई स्कोर या पुरस्कार नहीं।\n\nइंटरफेस उत्तेजित नहीं करता, ध्यान वीडियो पर रहता है।', id:'Tidak ada warna cerah. Tidak ada animasi. Tidak ada skor atau hadiah.\n\nAntarmuka tidak merangsang, perhatian tetap pada video.' },

    /* ── family section ── */
    familyLabel: { en:'Family', nl:'Gezin', de:'Familie', fr:'Famille', es:'Familia', it:'Famiglia', pt:'Família', ru:'Семья', ar:'العائلة', zh:'家庭', ja:'家族', ko:'가족', hi:'परिवार', id:'Keluarga' },
    familyH2:   { en:'Share lists between partners.', nl:'Deel lijsten tussen partners.', de:'Listen zwischen Partnern teilen.', fr:'Partagez les listes entre partenaires.', es:'Comparte listas entre parejas.', it:'Condividi le liste tra partner.', pt:'Compartilhe listas entre parceiros.', ru:'Делитесь списками между партнёрами.', ar:'شارك القوائم بين الوالدين.', zh:'在伴侣之间共享列表。', ja:'パートナー間でリストを共有。', ko:'파트너 간 목록 공유.', hi:'साझेदारों के बीच सूचियां साझा करें।', id:'Bagikan daftar antar pasangan.' },
    familyBody: { en:'Link your partner\'s phone via QR code. Your children\'s favourite videos are automatically shared between you, always up-to-date on both devices.\n\nYour subscription covers the whole family — your partner benefits too.', nl:'Koppel de telefoon van je partner via een QR-code. De favoriete filmpjes van je kinderen worden automatisch gedeeld tussen jullie, op beide toestellen altijd up-to-date.\n\nJe abonnement geldt voor het hele gezin, ook je partner profiteert ervan.', de:'Verbinde das Smartphone deines Partners via QR-Code. Die Lieblingsvideos eurer Kinder werden automatisch geteilt.\n\nDein Abo gilt für die ganze Familie.', fr:'Liez le téléphone de votre partenaire via QR code. Les vidéos préférées de vos enfants sont partagées automatiquement.\n\nVotre abonnement couvre toute la famille.', es:'Vincula el teléfono de tu pareja mediante QR. Los vídeos favoritos de vuestros hijos se comparten automáticamente.\n\nVuestra suscripción cubre toda la familia.', it:'Collega il telefono del tuo partner via QR. I video preferiti dei tuoi figli sono condivisi automaticamente.\n\nL\'abbonamento vale per tutta la famiglia.', pt:'Vincule o celular do seu parceiro via QR. Os vídeos favoritos das crianças são compartilhados automaticamente.\n\nSua assinatura cobre toda a família.', ru:'Подключите телефон партнёра по QR-коду. Любимые видео детей автоматически синхронизируются.\n\nПодписка распространяется на всю семью.', ar:'اربط هاتف شريكك عبر رمز QR. تتم مشاركة مقاطع الأطفال المفضلة تلقائياً.\n\nاشتراكك يشمل العائلة بأكملها.', zh:'通过二维码连接伴侣的手机。孩子的最爱视频自动共享，两台设备始终同步。\n\n您的订阅适用于整个家庭。', ja:'QRコードでパートナーのスマホと接続。子供のお気に入り動画が自動で共有されます。\n\nサブスクリプションは家族全員に有効です。', ko:'QR코드로 파트너 휴대폰을 연결하세요. 아이들의 즐겨찾기 영상이 자동으로 공유됩니다.\n\n구독은 온 가족이 사용 가능합니다.', hi:'QR कोड के जरिए अपने साथी का फोन लिंक करें। बच्चों के पसंदीदा वीडियो स्वचालित रूप से साझा होते हैं।\n\nआपकी सदस्यता पूरे परिवार के लिए है।', id:'Hubungkan ponsel pasangan Anda via QR. Video favorit anak-anak dibagikan secara otomatis.\n\nLangganan Anda berlaku untuk seluruh keluarga.' },

    /* ── boring/approach section ── */
    boringLabel:   { en:'Our approach', nl:'Onze aanpak', de:'Unser Ansatz', fr:'Notre approche', es:'Nuestro enfoque', it:'Il nostro approccio', pt:'Nossa abordagem', ru:'Наш подход', ar:'نهجنا', zh:'我们的理念', ja:'私たちのアプローチ', ko:'우리의 접근법', hi:'हमारा दृष्टिकोण', id:'Pendekatan kami' },
    boringH2:      { en:'This app is boring. On purpose.', nl:'Deze app is saai. En dat is expres.', de:'Diese App ist langweilig. Absichtlich.', fr:'Cette app est ennuyeuse. Exprès.', es:'Esta app es aburrida. A propósito.', it:'Questa app è noiosa. Di proposito.', pt:'Este app é chato. De propósito.', ru:'Это приложение скучное. Намеренно.', ar:'هذا التطبيق ممل. عن قصد.', zh:'这个应用很无聊。故意的。', ja:'このアプリは退屈です。意図的に。', ko:'이 앱은 지루합니다. 의도적으로.', hi:'यह ऐप उबाऊ है। जानबूझकर।', id:'Aplikasi ini membosankan. Sengaja.' },
    boringSub:     { en:"All video apps are addictive. This one isn't.", nl:'Alle videoapps zijn verslavend. Deze niet.', de:'Alle Video-Apps sind süchtig machend. Diese nicht.', fr:'Toutes les apps vidéo créent une dépendance. Pas celle-ci.', es:'Todas las apps de vídeo son adictivas. Esta no.', it:'Tutte le app video creano dipendenza. Questa no.', pt:'Todos os apps de vídeo são viciantes. Este não.', ru:'Все видеоприложения вызывают зависимость. Это — нет.', ar:'جميع تطبيقات الفيديو مُسبِّبة للإدمان. هذا لا.', zh:'所有视频应用都令人上瘾。这个不会。', ja:'すべての動画アプリは依存性があります。このアプリは違います。', ko:'모든 동영상 앱은 중독성이 있습니다. 이 앱은 아닙니다.', hi:'सभी वीडियो ऐप्स नशे की लत हैं। यह नहीं।', id:'Semua aplikasi video membuat ketagihan. Yang ini tidak.' },
    strikeNotif:   { en:'No notifications', nl:'Geen notificaties', de:'Keine Benachrichtigungen', fr:'Pas de notifications', es:'Sin notificaciones', it:'Nessuna notifica', pt:'Sem notificações', ru:'Без уведомлений', ar:'لا إشعارات', zh:'无推送通知', ja:'通知なし', ko:'알림 없음', hi:'कोई सूचना नहीं', id:'Tanpa notifikasi' },
    strikeColors:  { en:'No bright colours', nl:'Geen felle kleuren', de:'Keine grellen Farben', fr:'Pas de couleurs vives', es:'Sin colores llamativos', it:'Nessun colore vivace', pt:'Sem cores chamativas', ru:'Без ярких цветов', ar:'لا ألوان صاخبة', zh:'无鲜艳色彩', ja:'派手な色なし', ko:'화려한 색상 없음', hi:'कोई चमकीले रंग नहीं', id:'Tanpa warna mencolok' },
    strikeScores:  { en:'No scores or rewards', nl:'Geen scores of beloningen', de:'Keine Punkte oder Belohnungen', fr:'Pas de scores ni récompenses', es:'Sin puntuaciones ni recompensas', it:'Nessun punteggio o ricompensa', pt:'Sem pontuações ou recompensas', ru:'Без очков и наград', ar:'لا نقاط ولا مكافآت', zh:'无积分或奖励', ja:'スコアや報酬なし', ko:'점수나 보상 없음', hi:'कोई स्कोर या पुरस्कार नहीं', id:'Tanpa skor atau hadiah' },
    strikeAddiction: { en:'No addictive elements', nl:'Geen verslavingselementen', de:'Keine Sucht-Elemente', fr:'Pas d\'éléments addictifs', es:'Sin elementos adictivos', it:'Nessun elemento che crea dipendenza', pt:'Sem elementos viciantes', ru:'Без элементов зависимости', ar:'لا عناصر إدمانية', zh:'无成瘾元素', ja:'依存性の要素なし', ko:'중독성 요소 없음', hi:'कोई लत लगाने वाले तत्व नहीं', id:'Tanpa elemen adiktif' },

    /* ── no data section ── */
    noDataLabel:    { en:'Privacy', nl:'Privacy', de:'Datenschutz', fr:'Confidentialité', es:'Privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'الخصوصية', zh:'隐私', ja:'プライバシー', ko:'개인정보', hi:'गोपनीयता', id:'Privasi' },
    noDataH2:       { en:"We don't want your data.", nl:'Wij willen jouw data niet.', de:'Wir wollen deine Daten nicht.', fr:'Nous ne voulons pas de vos données.', es:'No queremos tus datos.', it:'Non vogliamo i tuoi dati.', pt:'Não queremos os seus dados.', ru:'Нам не нужны ваши данные.', ar:'لا نريد بياناتك.', zh:'我们不需要你的数据。', ja:'あなたのデータは必要ありません。', ko:'당신의 데이터가 필요 없습니다.', hi:'हमें आपका डेटा नहीं चाहिए।', id:'Kami tidak menginginkan data Anda.' },
    noDataSub:      { en:"And definitely not your child's.", nl:'En zeker niet die van je kind.', de:'Und schon gar nicht die deines Kindes.', fr:"Et surtout pas celles de votre enfant.", es:'Y definitivamente no los de tu hijo.', it:'E tantomeno quelli di tuo figlio.', pt:'E definitivamente não os do seu filho.', ru:'И уж точно не данные вашего ребёнка.', ar:'وبالتأكيد ليس بيانات طفلك.', zh:'更不需要你孩子的。', ja:'お子さんのデータも絶対に。', ko:'자녀의 데이터도 절대 필요 없습니다.', hi:'और बिल्कुल भी आपके बच्चे का नहीं।', id:'Apalagi data anak Anda.' },
    noDataBody:     { en:"We store just a user ID, a nickname for your kid and their favourite videos. That's it.", nl:"We slaan alleen een gebruikersnummer, een bijnaam voor je kind en zijn of haar favoriete video's op. Dat is alles.", de:'Wir speichern nur eine Benutzer-ID, einen Spitznamen für dein Kind und seine Lieblingsvideos. Das war es.', fr:"Nous stockons uniquement un identifiant, un surnom pour votre enfant et ses vidéos préférées. C'est tout.", es:'Solo guardamos un ID de usuario, un apodo para tu hijo y sus videos favoritos. Eso es todo.', it:"Salviamo solo un ID utente, un soprannome per tuo figlio e i suoi video preferiti. Tutto qui.", pt:'Armazenamos apenas um ID de usuário, um apelido para seu filho e seus vídeos favoritos. Só isso.', ru:'Мы храним только идентификатор пользователя, псевдоним ребёнка и его любимые видео. Всё.', ar:'نحتفظ فقط بمعرّف المستخدم ولقب طفلك وفيديوهاته المفضلة. هذا كل شيء.', zh:'我们只保存一个用户ID、孩子的昵称和他的收藏视频。仅此而已。', ja:'ユーザーID、お子さんのニックネーム、お気に入り動画だけを保存します。それだけです。', ko:'사용자 ID, 자녀의 닉네임, 좋아하는 동영상만 저장합니다. 그게 전부입니다.', hi:'हम केवल एक यूजर ID, बच्चे का उपनाम और पसंदीदा वीडियो सहेजते हैं। बस इतना ही।', id:'Kami hanya menyimpan ID pengguna, nama panggilan anak, dan video favorit mereka. Itu saja.' },

    /* ── CTA ── */
    ctaH2:  { en:'Ready to start?', nl:'Klaar om te beginnen?', de:'Bereit loszulegen?', fr:'Prêt à commencer ?', es:'¿Listo para empezar?', it:'Pronto per iniziare?', pt:'Pronto para começar?', ru:'Готовы начать?', ar:'مستعد للبدء؟', zh:'准备好了吗？', ja:'始める準備はできていますか？', ko:'시작할 준비가 됐나요?', hi:'शुरू करने के लिए तैयार हैं?', id:'Siap memulai?' },
    ctaBody: { en:'Add your first child and choose a video. Just one.', nl:'Voeg je eerste kind toe en kies een video. Gewoon één.', de:'Füge dein erstes Kind hinzu und wähle ein Video. Nur eines.', fr:'Ajoutez votre premier enfant et choisissez une vidéo. Une seule.', es:'Añade tu primer hijo y elige un vídeo. Solo uno.', it:'Aggiungi il tuo primo figlio e scegli un video. Solo uno.', pt:'Adicione seu primeiro filho e escolha um vídeo. Apenas um.', ru:'Добавьте первого ребёнка и выберите видео. Всего одно.', ar:'أضف طفلك الأول واختر مقطعاً. واحداً فقط.', zh:'添加您的第一个孩子并选择一个视频。就一个。', ja:'最初の子供を追加して動画を選んでください。たった1本です。', ko:'첫 번째 아이를 추가하고 영상을 선택하세요. 딱 하나만.', hi:'अपना पहला बच्चा जोड़ें और एक वीडियो चुनें। बस एक।', id:'Tambahkan anak pertama Anda dan pilih video. Hanya satu.' },

    /* ── footer ── */
    footerPrivacy: { en:'Privacy Policy', nl:'Privacybeleid', de:'Datenschutz', fr:'Politique de confidentialité', es:'Política de privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'سياسة الخصوصية', zh:'隐私政策', ja:'プライバシーポリシー', ko:'개인정보 처리방침', hi:'गोपनीयता नीति', id:'Kebijakan Privasi' },
    footerTerms:   { en:'Terms of Service', nl:'Gebruiksvoorwaarden', de:'Nutzungsbedingungen', fr:'CGU', es:'Términos de servicio', it:'Termini di servizio', pt:'Termos de serviço', ru:'Условия использования', ar:'شروط الخدمة', zh:'服务条款', ja:'利用規約', ko:'서비스 약관', hi:'सेवा की शर्तें', id:'Syarat Layanan' },
  };

  function getLang() {
    const saved = localStorage.getItem('pov_lang');
    if (saved && T.navAffiliate[saved]) return saved;
    const browser = (navigator.language || 'en').substring(0, 2).toLowerCase();
    return T.navAffiliate[browser] ? browser : 'en';
  }

  function applyLang(lang) {
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (T[key] && T[key][lang] !== undefined) {
        el.textContent = T[key][lang];
      }
    });
    // Update select
    const sel = document.getElementById('lang-select');
    if (sel) sel.value = lang;
  }

  function buildSelector() {
    const sel = document.createElement('select');
    sel.id = 'lang-select';
    sel.style.cssText = 'background:transparent;border:none;font-size:13px;font-weight:500;color:var(--muted);cursor:pointer;font-family:inherit;padding:2px 4px;border-radius:4px;';
    sel.title = 'Language';
    Object.entries(LANGS).forEach(([code, name]) => {
      const opt = document.createElement('option');
      opt.value = code;
      opt.textContent = name;
      sel.appendChild(opt);
    });
    sel.value = getLang();
    sel.addEventListener('change', () => {
      localStorage.setItem('pov_lang', sel.value);
      applyLang(sel.value);
    });
    return sel;
  }

  document.addEventListener('DOMContentLoaded', () => {
    const navLinks = document.querySelector('.nav-links');
    if (navLinks) {
      const li = document.createElement('li');
      li.appendChild(buildSelector());
      navLinks.appendChild(li);
    }
    applyLang(getLang());
  });
})();
