/* PlayOneVideo — website i18n.
   Wordt zowel in de browser ingeladen als door build.js (Node) gelezen
   om statische locale-subpaths (/nl/, /de/, ...) te genereren. */
(function (globalScope) {
  const LANGS = {
    en: 'English', nl: 'Nederlands', de: 'Deutsch', fr: 'Français',
    es: 'Español', it: 'Italiano', pt: 'Português', ru: 'Русский',
    ar: 'العربية', zh: '中文', ja: '日本語', ko: '한국어',
    hi: 'हिन्दी', id: 'Bahasa Indonesia',
  };

  const T = {
    /* ── nav ── */
    navAffiliate: { en:'Affiliate', nl:'Word affiliate', de:'Affiliate', fr:'Affilié', es:'Afiliado', it:'Affiliato', pt:'Afiliado', ru:'Партнёрство', ar:'شراكة', zh:'推广合作', ja:'アフィリエイト', ko:'제휴', hi:'सहयोगी', id:'Afiliasi' },
    navPrivacy:   { en:'Privacy', nl:'Privacy', de:'Datenschutz', fr:'Confidentialité', es:'Privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'الخصوصية', zh:'隐私', ja:'プライバシー', ko:'개인정보', hi:'गोपनीयता', id:'Privasi' },
    navTerms:     { en:'Terms', nl:'Voorwaarden', de:'AGB', fr:'CGU', es:'Términos', it:'Termini', pt:'Termos', ru:'Условия', ar:'الشروط', zh:'条款', ja:'利用規約', ko:'이용약관', hi:'शर्तें', id:'Syarat' },

    /* ── hero ── */
    heroH1:    { en:'Let kids watch one video.', nl:'Laat kinderen één filmpje kijken.', de:'Lass Kinder ein Video ansehen.', fr:'Laissez les enfants regarder une vidéo.', es:'Deja que los niños vean un vídeo.', it:'Lascia che i bambini guardino un video.', pt:'Deixe as crianças assistir um vídeo.', ru:'Позвольте ребёнку посмотреть одно видео.', ar:'دع الأطفال يشاهدون مقطعاً واحداً.', zh:'让孩子看一个视频。', ja:'子供に動画を1本見せよう。', ko:'아이가 영상 하나를 보게 하세요.', hi:'बच्चों को एक वीडियो देखने दें।', id:'Biarkan anak menonton satu video.' },
    heroSub:   { en:'Use YouTube in a child-friendly way.\n\nNo suggestions.\nNo clicking through.\nNo arguments.', nl:'Gebruik YouTube op een kindvriendelijke manier.\n\nGeen suggesties.\nNiet doorklikken.\nGeen ruzie.', de:'Nutze YouTube auf eine kindergerechte Weise.\n\nKeine Vorschläge.\nKein Weiterklicken.\nKein Streit.', fr:'Utilisez YouTube de façon adaptée aux enfants.\n\nPas de suggestions.\nPas de navigation aléatoire.\nPas de disputes.', es:'Usa YouTube de forma adaptada a los niños.\n\nSin sugerencias.\nSin hacer clic en otros.\nSin discusiones.', it:'Usa YouTube in modo adatto ai bambini.\n\nNiente suggerimenti.\nNiente clic su altri video.\nNiente litigi.', pt:'Use o YouTube de forma adequada para crianças.\n\nSem sugestões.\nSem clicar em outros.\nSem brigas.', ru:'Используйте YouTube безопасно для детей.\n\nНикаких рекомендаций.\nНикаких переходов.\nНикаких споров.', ar:'استخدم YouTube بطريقة مناسبة للأطفال.\n\nلا اقتراحات.\nلا نقر على مقاطع أخرى.\nلا جدالات.', zh:'以儿童友好的方式使用YouTube。\n\n没有推荐。\n不乱点击。\n没有争吵。', ja:'子供に安全なYouTubeの使い方。\n\nおすすめなし。\n他の動画へのクリックなし。\n言い争いなし。', ko:'아이에게 안전한 YouTube 사용법。\n\n추천 없음。\n다른 영상 클릭 없음。\n다툼 없음。', hi:'बच्चों के लिए YouTube का सुरक्षित उपयोग।\n\nकोई सुझाव नहीं।\nआगे क्लिक नहीं।\nकोई झगड़ा नहीं।', id:'Gunakan YouTube dengan cara yang ramah anak.\n\nTanpa saran.\nTanpa klik video lain.\nTanpa pertengkaran.' },
    heroPrice: { en:'14 days free, then $1.99 per month. Cancel anytime.', nl:'14 dagen gratis, daarna €1,99 per maand. Opzegbaar wanneer je wilt.', de:'14 Tage kostenlos, dann €1,99 pro Monat. Jederzeit kündbar.', fr:'14 jours gratuits, puis 1,99 €/mois. Annulable à tout moment.', es:'14 días gratis, luego €1,99/mes. Cancela cuando quieras.', it:'14 giorni gratis, poi €1,99/mese. Disdici quando vuoi.', pt:'14 dias grátis, depois R$10,90/mês. Cancele quando quiser.', ru:'14 дней бесплатно, затем 199 ₽ в месяц. Отмена в любое время.', ar:'14 يوماً مجاناً، ثم 7.99 ر.س شهرياً. إلغاء في أي وقت.', zh:'免费14天，之后每月¥18。随时可取消。', ja:'14日間無料、その後月¥300。いつでもキャンセル可。', ko:'14일 무료, 이후 월 ₩3,300. 언제든지 취소 가능.', hi:'14 दिन मुफ्त, फिर ₹160/माह। कभी भी रद्द करें।', id:'14 hari gratis, lalu Rp32.000/bulan. Batalkan kapan saja.' },
    heroComingSoon: { en:'coming soon', nl:'binnenkort', de:'bald verfügbar', fr:'bientôt', es:'próximamente', it:'presto', pt:'em breve', ru:'скоро', ar:'قريباً', zh:'即将推出', ja:'近日公開', ko:'곧 출시', hi:'जल्द आ रहा है', id:'segera hadir' },

    /* ── problem section ── */
    problemLabel: { en:'The problem', nl:'Het probleem', de:'Das Problem', fr:'Le problème', es:'El problema', it:'Il problema', pt:'O problema', ru:'Проблема', ar:'المشكلة', zh:'问题', ja:'問題', ko:'문제', hi:'समस्या', id:'Masalah' },
    problemH2:    { en:'Sound familiar?', nl:'Ken je dit?', de:'Kennt ihr das?', fr:'Ça vous parle ?', es:'¿Te suena?', it:'Ti suona familiare?', pt:'Familiar?', ru:'Узнаёте?', ar:'هل هذا مألوف؟', zh:'听起来熟悉吗？', ja:'よくある話では？', ko:'익숙한 상황인가요?', hi:'पहचाना?', id:'Familiar?' },
    problemBody:  { en:'Your child is allowed to watch 1 video.', nl:'Je kind mag 1 filmpje kijken.', de:'Dein Kind darf 1 Video ansehen.', fr:'Votre enfant a le droit de regarder 1 vidéo.', es:'Tu hijo puede ver 1 vídeo.', it:'Tuo figlio può guardare 1 video.', pt:'Seu filho pode assistir 1 vídeo.', ru:'Ребёнку можно посмотреть 1 видео.', ar:'يُسمح لطفلك بمشاهدة مقطع واحد.', zh:'孩子只能看1个视频。', ja:'子供が見ていいのはビデオ1本だけ。', ko:'아이가 영상 1개만 볼 수 있는데.', hi:'बच्चे को 1 वीडियो देखने की अनुमति है।', id:'Anak Anda boleh menonton 1 video.' },
    calloutLine1: { en:'Scrolls around.', nl:'Scrollt door.', de:'Scrollt weiter.', fr:'Il fait défiler.', es:'Se pone a hacer scroll.', it:'Scorre avanti.', pt:'Fica rolando.', ru:'Листает.', ar:'يتصفّح.', zh:'开始滑屏。', ja:'スクロールしはじめる。', ko:'스크롤하다가.', hi:'स्क्रॉल करता है।', id:'Malah scroll.' },
    calloutLine2: { en:'Clicks away.', nl:'Klikt door.', de:'Klickt weiter.', fr:'Clique sur autre chose.', es:'Hace clic en todo.', it:'Clicca ovunque.', pt:'Fica clicando.', ru:'Кликает дальше.', ar:'ينقر ويتنقّل.', zh:'乱点视频。', ja:'クリックしてしまう。', ko:'이것저것 클릭.', hi:'क्लिक करता है।', id:'Klik sana-sini.' },
    calloutLine3: { en:'Arguments.', nl:'Ruzie.', de:'Streit.', fr:'Disputes.', es:'Discusiones.', it:'Litigi.', pt:'Briga.', ru:'Скандал.', ar:'شجار.', zh:'争吵。', ja:'言い争い。', ko:'다툼.', hi:'झगड़ा।', id:'Bertengkar.' },

    /* ── approach section ── */
    approachLabel: { en:'Our approach', nl:'Onze aanpak', de:'Unser Ansatz', fr:'Notre approche', es:'Nuestro enfoque', it:'Il nostro approccio', pt:'Nossa abordagem', ru:'Наш подход', ar:'مقاربتنا', zh:'我们的方法', ja:'私たちのアプローチ', ko:'우리의 접근법', hi:'हमारा दृष्टिकोण', id:'Pendekatan kami' },
    approachH2:    { en:'All video apps make kids addicted.', nl:'Alle videoapps maken kinderen verslaafd.', de:'Alle Video-Apps machen Kinder süchtig.', fr:'Toutes les applis vidéo rendent les enfants accros.', es:'Todas las apps de vídeo enganchan a los niños.', it:'Tutte le app video creano dipendenza nei bambini.', pt:'Todos os apps de vídeo viciam as crianças.', ru:'Все видеоприложения вызывают зависимость у детей.', ar:'كل تطبيقات الفيديو تُدمن الأطفال.', zh:'所有视频应用都让孩子上瘾。', ja:'すべての動画アプリが子供を依存させる。', ko:'모든 동영상 앱이 아이를 중독시킵니다.', hi:'सभी वीडियो ऐप्स बच्चों को लत लगा देते हैं।', id:'Semua aplikasi video membuat anak kecanduan.' },
    approachBody:  { en:'This app is intentionally boring. It plays one video.', nl:'Deze app is expres saai. Hij speelt één video af.', de:'Diese App ist absichtlich langweilig. Sie spielt ein Video ab.', fr:'Cette appli est volontairement ennuyeuse. Elle joue une seule vidéo.', es:'Esta app es aburrida a propósito. Reproduce un vídeo.', it:'Questa app è volutamente noiosa. Riproduce un solo video.', pt:'Este app é propositalmente chato. Ele toca um vídeo.', ru:'Это приложение намеренно скучное. Оно воспроизводит одно видео.', ar:'هذا التطبيق مُصمَّم ليكون مملاً. يشغّل مقطعاً واحداً فقط.', zh:'这款应用故意设计得无聊。它只播放一个视频。', ja:'このアプリは意図的につまらなく作られています。動画を1本再生するだけです。', ko:'이 앱은 의도적으로 지루하게 만들었습니다. 영상 하나만 재생합니다.', hi:'यह ऐप जानबूझकर नीरस है। यह एक वीडियो चलाता है।', id:'Aplikasi ini sengaja dibuat membosankan. Ia memutar satu video.' },
    feat1Title: { en:'No bright colours', nl:'Geen felle kleuren', de:'Keine grellen Farben', fr:'Pas de couleurs vives', es:'Sin colores llamativos', it:'Nessun colore sgargiante', pt:'Sem cores vivas', ru:'Никаких ярких цветов', ar:'لا ألوان صارخة', zh:'无鲜艳颜色', ja:'派手な色なし', ko:'밝은 색상 없음', hi:'चमकीले रंग नहीं', id:'Tidak ada warna cerah' },
    feat1Body: { en:'Calm interface. Attention on the video, not the app.', nl:'Rustige interface. Aandacht bij het filmpje, niet bij de app.', de:'Ruhige Oberfläche. Aufmerksamkeit auf das Video, nicht auf die App.', fr:'Interface apaisante. Attention sur la vidéo, pas sur l\'appli.', es:'Interfaz tranquila. Atención en el vídeo, no en la app.', it:'Interfaccia tranquilla. Attenzione al video, non all\'app.', pt:'Interface calma. Atenção no vídeo, não no app.', ru:'Спокойный интерфейс. Внимание на видео, а не на приложении.', ar:'واجهة هادئة. التركيز على الفيديو، لا على التطبيق.', zh:'平静的界面。注意力放在视频上，而非应用。', ja:'落ち着いたインターフェース。注意はアプリではなく動画へ。', ko:'차분한 인터페이스. 앱이 아닌 영상에 집중.', hi:'शांत इंटरफेस। ध्यान वीडियो पर, ऐप पर नहीं।', id:'Antarmuka tenang. Perhatian pada video, bukan aplikasi.' },
    feat2Title: { en:'No animations', nl:'Geen animaties', de:'Keine Animationen', fr:'Pas d\'animations', es:'Sin animaciones', it:'Nessuna animazione', pt:'Sem animações', ru:'Никакой анимации', ar:'لا رسوم متحركة', zh:'无动画', ja:'アニメーションなし', ko:'애니메이션 없음', hi:'कोई एनिमेशन नहीं', id:'Tidak ada animasi' },
    feat2Body: { en:'Nothing that stimulates or distracts.', nl:'Niets dat prikkelt of afleidt.', de:'Nichts, das stimuliert oder ablenkt.', fr:'Rien qui stimule ou distrait.', es:'Nada que estimule o distraiga.', it:'Niente che stimoli o distragga.', pt:'Nada que estimule ou distraia.', ru:'Ничего, что стимулирует или отвлекает.', ar:'لا شيء يُحفّز أو يُشتّت.', zh:'没有任何刺激或分散注意力的东西。', ja:'刺激したり気を散らすものは何もない。', ko:'자극하거나 산만하게 만드는 것 없음.', hi:'कोई उत्तेजना या विकर्षण नहीं।', id:'Tidak ada yang merangsang atau mengalihkan perhatian.' },
    feat3Title: { en:'No scores or rewards', nl:'Geen scores of beloningen', de:'Keine Punkte oder Belohnungen', fr:'Pas de scores ni de récompenses', es:'Sin puntuaciones ni recompensas', it:'Nessun punteggio o premio', pt:'Sem pontuações ou recompensas', ru:'Никаких очков или наград', ar:'لا نقاط ولا مكافآت', zh:'无得分或奖励', ja:'得点も報酬もなし', ko:'점수나 보상 없음', hi:'कोई स्कोर या पुरस्कार नहीं', id:'Tidak ada skor atau hadiah' },
    feat3Body: { en:'No likes, streaks or points to come back for.', nl:'Geen likes, streaks of punten om op terug te komen.', de:'Keine Likes, Streaks oder Punkte, die zum Wiederkommen verleiten.', fr:'Pas de likes, séries ou points pour revenir.', es:'Sin me gusta, rachas ni puntos para volver.', it:'Nessun like, serie o punto per tornare.', pt:'Sem curtidas, sequências ou pontos para voltar.', ru:'Никаких лайков, серий или очков, ради которых хочется вернуться.', ar:'لا إعجابات ولا سلاسل ولا نقاط تجعلك تعود.', zh:'没有点赞、连续天数或积分让你回来。', ja:'戻ってくる理由となるいいね！、ストリーク、ポイントなし。', ko:'다시 오게 만드는 좋아요, 연속 기록, 포인트 없음.', hi:'वापस आने के लिए कोई लाइक, स्ट्रीक या पॉइंट नहीं।', id:'Tidak ada suka, streak, atau poin untuk kembali.' },
    feat4Title: { en:'Intentionally boring', nl:'Expres saai', de:'Absichtlich langweilig', fr:'Volontairement ennuyeux', es:'Aburrida a propósito', it:'Volutamente noioso', pt:'Propositalmente chato', ru:'Намеренно скучное', ar:'مملّ عمداً', zh:'故意无聊', ja:'意図的につまらない', ko:'의도적으로 지루한', hi:'जानबूझकर नीरस', id:'Sengaja membosankan' },
    feat4Body: { en:'Designed to be as little addictive as possible.', nl:'Ontworpen om zo min mogelijk verslavend te zijn.', de:'Entworfen, um so wenig wie möglich süchtig zu machen.', fr:'Conçu pour être le moins addictif possible.', es:'Diseñada para ser lo menos adictiva posible.', it:'Progettato per essere il meno possibile dipendente.', pt:'Projetado para ser o menos viciante possível.', ru:'Разработано так, чтобы вызывать как можно меньше зависимости.', ar:'مُصمَّم ليكون أقل إدماناً ممكناً.', zh:'设计上尽可能减少成瘾性。', ja:'できる限り依存性が少なくなるよう設計されています。', ko:'최대한 중독성이 없도록 설계되었습니다.', hi:'यथासंभव कम नशे की लत के लिए डिज़ाइन किया गया।', id:'Dirancang untuk sesedikit mungkin membuat kecanduan.' },

    /* ── how it works ── */
    howLabel: { en:'How it works', nl:'Hoe het werkt', de:'So funktioniert\'s', fr:'Comment ça marche', es:'Cómo funciona', it:'Come funziona', pt:'Como funciona', ru:'Как это работает', ar:'كيف يعمل', zh:'如何运作', ja:'使い方', ko:'작동 방식', hi:'यह कैसे काम करता है', id:'Cara kerjanya' },
    howH2:    { en:'It\'s that simple.', nl:'Zo simpel is het.', de:'So einfach ist das.', fr:'C\'est aussi simple que ça.', es:'Así de sencillo.', it:'È così semplice.', pt:'É simples assim.', ru:'Всё просто.', ar:'الأمر بهذه البساطة.', zh:'就是这么简单。', ja:'それだけシンプル。', ko:'이렇게 간단합니다.', hi:'बस इतना ही सरल।', id:'Sesederhana itu.' },
    step1: { en:'Select a video', nl:'Klik een filmpje aan', de:'Video auswählen', fr:'Choisir une vidéo', es:'Elige un vídeo', it:'Seleziona un video', pt:'Escolha um vídeo', ru:'Выберите видео', ar:'اختر مقطعاً', zh:'选择一个视频', ja:'動画を選ぶ', ko:'영상 선택', hi:'एक वीडियो चुनें', id:'Pilih video' },
    step2: { en:'Child watches calmly', nl:'Kind kijkt rustig', de:'Kind schaut ruhig', fr:'L\'enfant regarde tranquillement', es:'El niño mira tranquilo', it:'Il bambino guarda tranquillo', pt:'A criança assiste calmamente', ru:'Ребёнок спокойно смотрит', ar:'يشاهد الطفل بهدوء', zh:'孩子安静地观看', ja:'子供が落ち着いて見る', ko:'아이가 조용히 시청', hi:'बच्चा शांति से देखता है', id:'Anak menonton dengan tenang' },
    step3: { en:'Screen goes black', nl:'Scherm wordt zwart', de:'Bildschirm wird schwarz', fr:'L\'écran devient noir', es:'La pantalla se vuelve negra', it:'Lo schermo diventa nero', pt:'A tela fica preta', ru:'Экран гаснет', ar:'تسودّ الشاشة', zh:'屏幕变黑', ja:'画面が暗くなる', ko:'화면이 꺼짐', hi:'स्क्रीन काली हो जाती है', id:'Layar menjadi hitam' },

    /* ── design section ── */
    designLabel: { en:'Design', nl:'Ontwerp', de:'Design', fr:'Design', es:'Diseño', it:'Design', pt:'Design', ru:'Дизайн', ar:'التصميم', zh:'设计', ja:'デザイン', ko:'디자인', hi:'डिज़ाइन', id:'Desain' },
    designH2:   { en:'Intentionally boring.', nl:'Expres saai.', de:'Absichtlich langweilig.', fr:'Volontairement ennuyeux.', es:'Aburrida a propósito.', it:'Volutamente noioso.', pt:'Propositalmente chato.', ru:'Намеренно скучное.', ar:'مملّ عمداً.', zh:'故意无聊。', ja:'意図的につまらない。', ko:'의도적으로 지루한.', hi:'जानबूझकर नीरस।', id:'Sengaja membosankan.' },
    designBody: { en:'No bright colours. No animations. No scores or rewards.\n\nThe interface does not stimulate, so attention stays on the video and not on the app. The app is designed to be as little addictive as possible.', nl:'Geen felle kleuren. Geen animaties. Geen scores of beloningen.\n\nDe interface prikkelt niet, zodat de aandacht bij het filmpje blijft en niet bij de app. De app is ontworpen om zo min mogelijk verslavend te zijn.', de:'Keine grellen Farben. Keine Animationen. Keine Punkte oder Belohnungen.\n\nDie Oberfläche stimuliert nicht, sodass die Aufmerksamkeit beim Video bleibt und nicht bei der App.', fr:'Pas de couleurs vives. Pas d\'animations. Pas de scores ni de récompenses.\n\nL\'interface ne stimule pas, l\'attention reste sur la vidéo et non sur l\'appli.', es:'Sin colores llamativos. Sin animaciones. Sin puntuaciones ni recompensas.\n\nLa interfaz no estimula, la atención se queda en el vídeo.', it:'Nessun colore sgargiante. Nessuna animazione. Nessun punteggio o premio.\n\nL\'interfaccia non stimola, l\'attenzione rimane sul video.', pt:'Sem cores vivas. Sem animações. Sem pontuações ou recompensas.\n\nA interface não estimula, a atenção fica no vídeo.', ru:'Никаких ярких цветов. Никакой анимации. Никаких очков или наград.\n\nИнтерфейс не стимулирует, поэтому внимание остаётся на видео.', ar:'لا ألوان صارخة. لا رسوم متحركة. لا نقاط ولا مكافآت.\n\nالواجهة لا تُحفّز، لذا يبقى التركيز على الفيديو.', zh:'无鲜艳颜色。无动画。无得分或奖励。\n\n界面不会刺激感官，注意力保持在视频上。', ja:'派手な色なし。アニメーションなし。得点も報酬もなし。\n\nインターフェースは刺激しないため、注意が動画に向けられます。', ko:'밝은 색상 없음. 애니메이션 없음. 점수나 보상 없음.\n\n인터페이스가 자극하지 않아 주의가 영상에 집중됩니다.', hi:'कोई चमकीले रंग नहीं। कोई एनिमेशन नहीं। कोई स्कोर या पुरस्कार नहीं।\n\nइंटरफेस उत्तेजित नहीं करता, ध्यान वीडियो पर रहता है।', id:'Tidak ada warna cerah. Tidak ada animasi. Tidak ada skor atau hadiah.\n\nAntarmuka tidak merangsang, perhatian tetap pada video.' },

    /* ── family section ── */
    familyLabel: { en:'Family', nl:'Gezin', de:'Familie', fr:'Famille', es:'Familia', it:'Famiglia', pt:'Família', ru:'Семья', ar:'العائلة', zh:'家庭', ja:'家族', ko:'가족', hi:'परिवार', id:'Keluarga' },
    familyH2:   { en:'Share lists between partners.', nl:'Deel lijsten tussen partners.', de:'Listen zwischen Partnern teilen.', fr:'Partagez les listes entre partenaires.', es:'Comparte listas entre parejas.', it:'Condividi le liste tra partner.', pt:'Compartilhe listas entre parceiros.', ru:'Делитесь списками между партнёрами.', ar:'شارك القوائم بين الوالدين.', zh:'在伴侣之间共享列表。', ja:'パートナー間でリストを共有。', ko:'파트너 간 목록 공유.', hi:'साझेदारों के बीच सूचियां साझा करें।', id:'Bagikan daftar antar pasangan.' },
    familyBody: { en:'Link your partner\'s phone via QR code. Your children\'s favourite videos are automatically shared between you, always up-to-date on both devices.\n\nYour subscription covers the whole family — your partner benefits too.', nl:'Koppel de telefoon van je partner via een QR-code. De favoriete filmpjes van je kinderen worden automatisch gedeeld tussen jullie, op beide toestellen altijd up-to-date.\n\nJe abonnement geldt voor het hele gezin, ook je partner profiteert ervan.', de:'Verbinde das Smartphone deines Partners via QR-Code. Die Lieblingsvideos eurer Kinder werden automatisch geteilt.\n\nDein Abo gilt für die ganze Familie.', fr:'Liez le téléphone de votre partenaire via QR code. Les vidéos préférées de vos enfants sont partagées automatiquement.\n\nVotre abonnement couvre toute la famille.', es:'Vincula el teléfono de tu pareja mediante QR. Los vídeos favoritos de vuestros hijos se comparten automáticamente.\n\nVuestra suscripción cubre toda la familia.', it:'Collega il telefono del tuo partner via QR. I video preferiti dei tuoi figli sono condivisi automaticamente.\n\nL\'abbonamento vale per tutta la famiglia.', pt:'Vincule o celular do seu parceiro via QR. Os vídeos favoritos das crianças são compartilhados automaticamente.\n\nSua assinatura cobre toda a família.', ru:'Подключите телефон партнёра по QR-коду. Любимые видео детей автоматически синхронизируются.\n\nПодписка распространяется на всю семью.', ar:'اربط هاتف شريكك عبر رمز QR. تتم مشاركة مقاطع الأطفال المفضلة تلقائياً.\n\nاشتراكك يشمل العائلة بأكملها.', zh:'通过二维码连接伴侣的手机。孩子的最爱视频自动共享，两台设备始终同步。\n\n您的订阅适用于整个家庭。', ja:'QRコードでパートナーのスマホと接続。子供のお気に入り動画が自動で共有されます。\n\nサブスクリプションは家族全員に有効です。', ko:'QR코드로 파트너 휴대폰을 연결하세요. 아이들의 즐겨찾기 영상이 자동으로 공유됩니다.\n\n구독은 온 가족이 사용 가능합니다.', hi:'QR कोड के जरिए अपने साथी का फोन लिंक करें। बच्चों के पसंदीदा वीडियो स्वचालित रूप से साझा होते हैं।\n\nआपकी सदस्यता पूरे परिवार के लिए है।', id:'Hubungkan ponsel pasangan Anda via QR. Video favorit anak-anak dibagikan secara otomatis.\n\nLangganan Anda berlaku untuk seluruh keluarga.' },

    /* ── boring/approach section ── */
    boringLabel:   { en:'Our approach', nl:'Onze aanpak', de:'Unser Ansatz', fr:'Notre approche', es:'Nuestro enfoque', it:'Il nostro approccio', pt:'Nossa abordagem', ru:'Наш подход', ar:'نهجنا', zh:'我们的理念', ja:'私たちのアプローチ', ko:'우리의 접근법', hi:'हमारा दृष्टिकोण', id:'Pendekatan kami' },
    boringH2:      { en:'This app is boring. On purpose.', nl:'Deze app is saai. En dat is expres.', de:'Diese App ist langweilig. Absichtlich.', fr:'Cette app est ennuyeuse. Exprès.', es:'Esta app es aburrida. A propósito.', it:'Questa app è noiosa. Di proposito.', pt:'Este app é chato. De propósito.', ru:'Это приложение скучное. Намеренно.', ar:'هذا التطبيق ممل. عن قصد.', zh:'这个应用很无聊。故意的。', ja:'このアプリは退屈です。意図的に。', ko:'이 앱은 지루합니다. 의도적으로.', hi:'यह ऐप उबाऊ है। जानबूझकर।', id:'Aplikasi ini membosankan. Sengaja.' },
    boringSub:     { en:"All video apps are addictive. This one isn't.", nl:'Alle videoapps zijn verslavend. Deze niet.', de:'Alle Video-Apps sind süchtig machend. Diese nicht.', fr:'Toutes les apps vidéo créent une dépendance. Pas celle-ci.', es:'Todas las apps de vídeo son adictivas. Esta no.', it:'Tutte le app video creano dipendenza. Questa no.', pt:'Todos os apps de vídeo são viciantes. Este não.', ru:'Все видеоприложения вызывают зависимость. Это — нет.', ar:'جميع تطبيقات الفيديو مُسبِّبة للإدمان. هذا لا.', zh:'所有视频应用都令人上瘾。这个不会。', ja:'すべての動画アプリは依存性があります。このアプリは違います。', ko:'모든 동영상 앱은 중독성이 있습니다. 이 앱은 아닙니다.', hi:'सभी वीडियो ऐप्स नशे की लत हैं। यह नहीं।', id:'Semua aplikasi video membuat ketagihan. Yang ini tidak.' },
    strikeNotif:   { en:'No notifications', nl:'Geen notificaties', de:'Keine Benachrichtigungen', fr:'Pas de notifications', es:'Sin notificaciones', it:'Nessuna notifica', pt:'Sem notificações', ru:'Без уведомлений', ar:'لا إشعارات', zh:'无推送通知', ja:'通知なし', ko:'알림 없음', hi:'कोई सूचना नहीं', id:'Tanpa notifikasi' },
    strikeColors:  { en:'No bright colours', nl:'Geen felle kleuren', de:'Keine grellen Farben', fr:'Pas de couleurs vives', es:'Sin colores llamativos', it:'Nessun colore vivace', pt:'Sem cores chamativas', ru:'Без ярких цветов', ar:'لا ألوان صاخبة', zh:'无鲜艳色彩', ja:'派手な色なし', ko:'화려한 색상 없음', hi:'कोई चमकीले रंग नहीं', id:'Tanpa warna mencolok' },
    strikeScores:  { en:'No scores or rewards', nl:'Geen scores of beloningen', de:'Keine Punkte oder Belohnungen', fr:'Pas de scores ni récompenses', es:'Sin puntuaciones ni recompensas', it:'Nessun punteggio o ricompensa', pt:'Sem pontuações ou recompensas', ru:'Без очков и наград', ar:'لا نقاط ولا مكافآت', zh:'无积分或奖励', ja:'スコアや報酬なし', ko:'점수나 보상 없음', hi:'कोई स्कोर या पुरस्कार नहीं', id:'Tanpa skor atau hadiah' },
    strikeAddiction: { en:'No addictive elements', nl:'Geen verslavingselementen', de:'Keine Sucht-Elemente', fr:'Pas d\'éléments addictifs', es:'Sin elementos adictivos', it:'Nessun elemento che crea dipendenza', pt:'Sem elementos viciantes', ru:'Без элементов зависимости', ar:'لا عناصر إدمانية', zh:'无成瘾元素', ja:'依存性の要素なし', ko:'중독성 요소 없음', hi:'कोई लत लगाने वाले तत्व नहीं', id:'Tanpa elemen adiktif' },

    /* ── no data section ── */
    noDataLabel:    { en:'Privacy', nl:'Privacy', de:'Datenschutz', fr:'Confidentialité', es:'Privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'الخصوصية', zh:'隐私', ja:'プライバシー', ko:'개인정보', hi:'गोपनीयता', id:'Privasi' },
    noDataH2:       { en:"We don't want your data.", nl:'Wij willen jouw data niet.', de:'Wir wollen deine Daten nicht.', fr:'Nous ne voulons pas de vos données.', es:'No queremos tus datos.', it:'Non vogliamo i tuoi dati.', pt:'Não queremos os seus dados.', ru:'Нам не нужны ваши данные.', ar:'لا نريد بياناتك.', zh:'我们不需要你的数据。', ja:'あなたのデータは必要ありません。', ko:'당신의 데이터가 필요 없습니다.', hi:'हमें आपका डेटा नहीं चाहिए।', id:'Kami tidak menginginkan data Anda.' },
    noDataSub:      { en:"And definitely not your child's.", nl:'En zeker niet die van je kind.', de:'Und schon gar nicht die deines Kindes.', fr:"Et surtout pas celles de votre enfant.", es:'Y definitivamente no los de tu hijo.', it:'E tantomeno quelli di tuo figlio.', pt:'E definitivamente não os do seu filho.', ru:'И уж точно не данные вашего ребёнка.', ar:'وبالتأكيد ليس بيانات طفلك.', zh:'更不需要你孩子的。', ja:'お子さんのデータも絶対に。', ko:'자녀의 데이터도 절대 필요 없습니다.', hi:'और बिल्कुल भी आपके बच्चे का नहीं।', id:'Apalagi data anak Anda.' },
    noDataBody:     { en:"We store just a user ID, a nickname for your kid and their favourite videos. That's it.", nl:"We slaan alleen een gebruikersnummer, een bijnaam voor je kind en zijn of haar favoriete video's op. Dat is alles.", de:'Wir speichern nur eine Benutzer-ID, einen Spitznamen für dein Kind und seine Lieblingsvideos. Das war es.', fr:"Nous stockons uniquement un identifiant, un surnom pour votre enfant et ses vidéos préférées. C'est tout.", es:'Solo guardamos un ID de usuario, un apodo para tu hijo y sus videos favoritos. Eso es todo.', it:"Salviamo solo un ID utente, un soprannome per tuo figlio e i suoi video preferiti. Tutto qui.", pt:'Armazenamos apenas um ID de usuário, um apelido para seu filho e seus vídeos favoritos. Só isso.', ru:'Мы храним только идентификатор пользователя, псевдоним ребёнка и его любимые видео. Всё.', ar:'نحتفظ فقط بمعرّف المستخدم ولقب طفلك وفيديوهاته المفضلة. هذا كل شيء.', zh:'我们只保存一个用户ID、孩子的昵称和他的收藏视频。仅此而已。', ja:'ユーザーID、お子さんのニックネーム、お気に入り動画だけを保存します。それだけです。', ko:'사용자 ID, 자녀의 닉네임, 좋아하는 동영상만 저장합니다. 그게 전부입니다.', hi:'हम केवल एक यूजर ID, बच्चे का उपनाम और पसंदीदा वीडियो सहेजते हैं। बस इतना ही।', id:'Kami hanya menyimpan ID pengguna, nama panggilan anak, dan video favorit mereka. Itu saja.' },

    /* ── CTA ── */
    ctaH2:  { en:'Ready to start?', nl:'Klaar om te beginnen?', de:'Bereit loszulegen?', fr:'Prêt à commencer ?', es:'¿Listo para empezar?', it:'Pronto per iniziare?', pt:'Pronto para começar?', ru:'Готовы начать?', ar:'مستعد للبدء؟', zh:'准备好了吗？', ja:'始める準備はできていますか？', ko:'시작할 준비가 됐나요?', hi:'शुरू करने के लिए तैयार हैं?', id:'Siap memulai?' },
    ctaBody: { en:'Add your first child and choose a video. Just one.', nl:'Voeg je eerste kind toe en kies een video. Gewoon één.', de:'Füge dein erstes Kind hinzu und wähle ein Video. Nur eines.', fr:'Ajoutez votre premier enfant et choisissez une vidéo. Une seule.', es:'Añade tu primer hijo y elige un vídeo. Solo uno.', it:'Aggiungi il tuo primo figlio e scegli un video. Solo uno.', pt:'Adicione seu primeiro filho e escolha um vídeo. Apenas um.', ru:'Добавьте первого ребёнка и выберите видео. Всего одно.', ar:'أضف طفلك الأول واختر مقطعاً. واحداً فقط.', zh:'添加您的第一个孩子并选择一个视频。就一个。', ja:'最初の子供を追加して動画を選んでください。たった1本です。', ko:'첫 번째 아이를 추가하고 영상을 선택하세요. 딱 하나만.', hi:'अपना पहला बच्चा जोड़ें और एक वीडियो चुनें। बस एक।', id:'Tambahkan anak pertama Anda dan pilih video. Hanya satu.' },

    /* ── footer ── */
    footerPrivacy: { en:'Privacy Policy', nl:'Privacybeleid', de:'Datenschutz', fr:'Politique de confidentialité', es:'Política de privacidad', it:'Privacy', pt:'Privacidade', ru:'Конфиденциальность', ar:'سياسة الخصوصية', zh:'隐私政策', ja:'プライバシーポリシー', ko:'개인정보 처리방침', hi:'गोपनीयता नीति', id:'Kebijakan Privasi' },
    footerTerms:   { en:'Terms of Service', nl:'Gebruiksvoorwaarden', de:'Nutzungsbedingungen', fr:'CGU', es:'Términos de servicio', it:'Termini di servizio', pt:'Termos de serviço', ru:'Условия использования', ar:'شروط الخدمة', zh:'服务条款', ja:'利用規約', ko:'서비스 약관', hi:'सेवा की शर्तें', id:'Syarat Layanan' },

    /* ── FAQ ── */
    faqLabel: { en:'Frequently Asked Questions', nl:'Veelgestelde vragen', de:'Häufig gestellte Fragen', fr:'Questions fréquentes', es:'Preguntas frecuentes', it:'Domande frequenti', pt:'Perguntas frequentes', ru:'Часто задаваемые вопросы', ar:'الأسئلة الشائعة', zh:'常见问题', ja:'よくある質問', ko:'자주 묻는 질문', hi:'अक्सर पूछे जाने वाले प्रश्न', id:'Pertanyaan Umum' },
    faqH2:    { en:'Your questions, answered.', nl:'Jouw vragen, beantwoord.', de:'Ihre Fragen, beantwortet.', fr:'Vos questions, avec réponses.', es:'Tus preguntas, respondidas.', it:'Le tue domande, con risposta.', pt:'Suas perguntas, respondidas.', ru:'Ваши вопросы и ответы.', ar:'أسئلتك مع إجاباتها.', zh:'您的问题，已解答。', ja:'よくある質問と回答。', ko:'자주 묻는 질문과 답변.', hi:'आपके सवाल, उनके जवाब।', id:'Pertanyaan Anda, Terjawab.' },

    faq1Q: { en:'What is PlayOneVideo?', nl:'Wat is PlayOneVideo?', de:'Was ist PlayOneVideo?', fr:'Qu\'est-ce que PlayOneVideo ?', es:'¿Qué es PlayOneVideo?', it:'Cos\'è PlayOneVideo?', pt:'O que é PlayOneVideo?', ru:'Что такое PlayOneVideo?', ar:'ما هو PlayOneVideo؟', zh:'什么是PlayOneVideo？', ja:'PlayOneVideoとは何ですか？', ko:'PlayOneVideo란 무엇인가요?', hi:'PlayOneVideo क्या है?', id:'Apa itu PlayOneVideo?' },
    faq1A: { en:'PlayOneVideo is an iOS app that lets parents choose exactly one YouTube video for their child to watch. When the video ends, the screen goes black. No autoplay, no recommendations, no scrolling — just the one video you chose.', nl:'PlayOneVideo is een iOS-app waarmee ouders precies één YouTube-video kiezen voor hun kind. Als de video afloopt, wordt het scherm zwart. Geen autoplay, geen aanbevelingen, geen scrollen.', de:'PlayOneVideo ist eine iOS-App, mit der Eltern genau ein YouTube-Video für ihr Kind auswählen. Wenn das Video endet, wird der Bildschirm schwarz. Kein Autoplay, keine Empfehlungen, kein Scrollen.', fr:'PlayOneVideo est une application iOS qui permet aux parents de choisir une seule vidéo YouTube pour leur enfant. Quand la vidéo se termine, l\'écran devient noir. Pas de lecture automatique, pas de recommandations, pas de défilement.', es:'PlayOneVideo es una app de iOS que permite a los padres elegir exactamente un vídeo de YouTube para su hijo. Cuando el vídeo termina, la pantalla se pone negra. Sin reproducción automática, sin recomendaciones, sin desplazamiento.', it:'PlayOneVideo è un\'app iOS che permette ai genitori di scegliere un solo video YouTube per il proprio figlio. Quando il video finisce, lo schermo diventa nero. Niente riproduzione automatica, niente consigli, niente scorrimento.', pt:'PlayOneVideo é um app iOS que permite aos pais escolher exatamente um vídeo do YouTube para o filho assistir. Quando o vídeo termina, a tela fica preta. Sem reprodução automática, sem recomendações, sem rolagem.', ru:'PlayOneVideo — iOS-приложение, позволяющее родителям выбрать ровно одно видео на YouTube для ребёнка. Когда видео заканчивается, экран гаснет. Никакого автовоспроизведения, рекомендаций или прокрутки.', ar:'PlayOneVideo تطبيق iOS يتيح للآباء اختيار مقطع يوتيوب واحد لمشاهدة أطفالهم. عند انتهاء المقطع تصبح الشاشة سوداء. لا تشغيل تلقائي، لا توصيات، لا تمرير.', zh:'PlayOneVideo是一款iOS应用，让父母为孩子精确选择一个YouTube视频。视频结束后屏幕变黑。没有自动播放，没有推荐，没有滚动。', ja:'PlayOneVideoは、親が子供のためにYouTube動画を1本だけ選べるiOSアプリです。動画が終わると画面が黒くなります。自動再生なし、おすすめなし、スクロールなし。', ko:'PlayOneVideo는 부모가 자녀를 위해 YouTube 동영상을 정확히 하나만 선택할 수 있는 iOS 앱입니다. 동영상이 끝나면 화면이 검게 변합니다. 자동 재생 없음, 추천 없음, 스크롤 없음.', hi:'PlayOneVideo एक iOS ऐप है जो माता-पिता को अपने बच्चे के लिए ठीक एक YouTube वीडियो चुनने देता है। वीडियो समाप्त होने पर स्क्रीन काली हो जाती है। कोई ऑटोप्ले नहीं, कोई सुझाव नहीं, कोई स्क्रॉलिंग नहीं।', id:'PlayOneVideo adalah aplikasi iOS yang memungkinkan orang tua memilih tepat satu video YouTube untuk ditonton anak. Saat video berakhir, layar menjadi hitam. Tanpa putar otomatis, tanpa rekomendasi, tanpa scrolling.' },

    faq2Q: { en:'Is this better than YouTube Kids?', nl:'Is dit beter dan YouTube Kids?', de:'Ist das besser als YouTube Kids?', fr:'Est-ce mieux que YouTube Kids ?', es:'¿Es mejor que YouTube Kids?', it:'È meglio di YouTube Kids?', pt:'É melhor que o YouTube Kids?', ru:'Лучше ли это, чем YouTube Kids?', ar:'هل هذا أفضل من YouTube Kids؟', zh:'这比YouTube Kids更好吗？', ja:'YouTube Kidsより良いですか？', ko:'YouTube Kids보다 더 좋은가요?', hi:'क्या यह YouTube Kids से बेहतर है?', id:'Apakah lebih baik dari YouTube Kids?' },
    faq2A: { en:'YouTube Kids still shows endless suggestions and autoplay. PlayOneVideo gives you complete control — you pick the video, the child watches it, the screen turns off. No feed, no recommendations, no way to click to something else.', nl:'YouTube Kids toont nog steeds eindeloze suggesties en autoplay. PlayOneVideo geeft je volledige controle: jij kiest de video, het kind kijkt, het scherm gaat uit. Geen feed, geen aanbevelingen, geen manier om door te klikken.', de:'YouTube Kids zeigt immer noch endlose Vorschläge und Autoplay. PlayOneVideo gibt dir die vollständige Kontrolle: Du wählst das Video, das Kind schaut, der Bildschirm geht aus. Kein Feed, keine Empfehlungen, kein Weiterklicken.', fr:'YouTube Kids montre encore des suggestions infinies et la lecture automatique. PlayOneVideo vous donne un contrôle total : vous choisissez la vidéo, l\'enfant la regarde, l\'écran s\'éteint. Aucun fil, aucune recommandation, impossible de cliquer ailleurs.', es:'YouTube Kids sigue mostrando sugerencias infinitas y reproducción automática. PlayOneVideo te da control total: tú eliges el vídeo, el niño lo ve, la pantalla se apaga. Sin feed, sin recomendaciones, sin posibilidad de hacer clic en otra cosa.', it:'YouTube Kids mostra ancora suggerimenti infiniti e riproduzione automatica. PlayOneVideo ti dà il controllo completo: scegli il video, il bambino lo guarda, lo schermo si spegne. Nessun feed, nessun consiglio, impossibile cliccare su altro.', pt:'O YouTube Kids ainda mostra sugestões infinitas e reprodução automática. PlayOneVideo dá controle total: você escolhe o vídeo, o filho assiste, a tela apaga. Sem feed, sem recomendações, sem como clicar em outra coisa.', ru:'YouTube Kids по-прежнему показывает бесконечные рекомендации и автовоспроизведение. PlayOneVideo даёт полный контроль: вы выбираете видео, ребёнок смотрит, экран гаснет. Никакой ленты, рекомендаций или возможности перейти на другое.', ar:'YouTube Kids لا يزال يعرض اقتراحات لا نهائية وتشغيلاً تلقائياً. يمنحك PlayOneVideo السيطرة الكاملة: أنت تختار المقطع، يشاهده الطفل، تنطفئ الشاشة. لا خلاصة، لا توصيات، لا طريقة للنقر على شيء آخر.', zh:'YouTube Kids仍然显示无尽的建议和自动播放。PlayOneVideo给你完全控制权：你选择视频，孩子观看，屏幕关闭。没有信息流，没有推荐，没有办法点击其他内容。', ja:'YouTube Kidsはまだ無限のおすすめと自動再生を表示します。PlayOneVideoは完全なコントロールを提供します：あなたが動画を選び、子供が視聴し、画面が消えます。フィードなし、おすすめなし、他のものをクリックできません。', ko:'YouTube Kids는 여전히 무한한 추천과 자동 재생을 보여줍니다. PlayOneVideo는 완전한 제어권을 줍니다: 부모가 동영상을 선택하고, 아이가 시청하고, 화면이 꺼집니다. 피드 없음, 추천 없음, 다른 것을 클릭할 방법 없음.', hi:'YouTube Kids अभी भी अंतहीन सुझाव और ऑटोप्ले दिखाता है। PlayOneVideo आपको पूरा नियंत्रण देता है: आप वीडियो चुनते हैं, बच्चा देखता है, स्क्रीन बंद हो जाती है। कोई फ़ीड नहीं, कोई सुझाव नहीं, कुछ और क्लिक करने का कोई तरीका नहीं।', id:'YouTube Kids masih menampilkan saran tanpa henti dan putar otomatis. PlayOneVideo memberi Anda kontrol penuh: Anda memilih video, anak menontonnya, layar mati. Tidak ada feed, tidak ada rekomendasi, tidak ada cara untuk mengklik hal lain.' },

    faq3Q: { en:'How much does PlayOneVideo cost?', nl:'Wat kost PlayOneVideo?', de:'Was kostet PlayOneVideo?', fr:'Combien coûte PlayOneVideo ?', es:'¿Cuánto cuesta PlayOneVideo?', it:'Quanto costa PlayOneVideo?', pt:'Quanto custa o PlayOneVideo?', ru:'Сколько стоит PlayOneVideo?', ar:'كم تكلفة PlayOneVideo؟', zh:'PlayOneVideo多少钱？', ja:'PlayOneVideoはいくらですか？', ko:'PlayOneVideo는 얼마인가요?', hi:'PlayOneVideo की कीमत क्या है?', id:'Berapa biaya PlayOneVideo?' },
    faq3A: { en:'PlayOneVideo starts with a 14-day free trial, then €1.99 per month. One subscription covers your whole family — your partner gets access too, at no extra charge.', nl:'PlayOneVideo begint met 14 dagen gratis, daarna €1,99 per maand. Eén abonnement dekt je hele gezin: je partner heeft ook toegang, zonder extra kosten.', de:'PlayOneVideo beginnt mit 14 Tagen kostenlos, danach 1,99 € pro Monat. Ein Abonnement deckt die ganze Familie ab – dein Partner hat auch Zugang, ohne Aufpreis.', fr:'PlayOneVideo commence par 14 jours d\'essai gratuit, puis 1,99 €/mois. Un abonnement couvre toute la famille — votre partenaire y a aussi accès sans supplément.', es:'PlayOneVideo comienza con 14 días de prueba gratis, luego €1,99 al mes. Una suscripción cubre a toda la familia: tu pareja también tiene acceso sin coste adicional.', it:'PlayOneVideo inizia con 14 giorni gratuiti, poi €1,99 al mese. Un abbonamento copre tutta la famiglia: anche il tuo partner ha accesso senza costi aggiuntivi.', pt:'PlayOneVideo começa com 14 dias grátis, depois €1,99 por mês. Uma assinatura cobre toda a família — seu parceiro também tem acesso sem custo extra.', ru:'PlayOneVideo начинается с 14 дней бесплатно, затем 1,99 € в месяц. Одна подписка покрывает всю семью — партнёр тоже получает доступ без доплаты.', ar:'يبدأ PlayOneVideo بتجربة مجانية 14 يوماً، ثم 1.99 يورو شهرياً. اشتراك واحد يغطي عائلتك بالكامل — شريكك أيضاً يحصل على وصول دون رسوم إضافية.', zh:'PlayOneVideo从14天免费试用开始，之后每月€1.99。一个订阅覆盖整个家庭，伴侣也可使用，无需额外费用。', ja:'PlayOneVideoは14日間無料トライアルから始まり、その後月額€1.99です。1つのサブスクリプションで家族全員をカバー。パートナーも追加料金なしでアクセスできます。', ko:'PlayOneVideo는 14일 무료 체험으로 시작하고, 이후 월 €1.99입니다. 구독 하나로 온 가족 커버 — 파트너도 추가 비용 없이 이용 가능합니다.', hi:'PlayOneVideo 14 दिन के मुफ्त ट्रायल से शुरू होता है, फिर प्रति माह €1.99। एक सब्सक्रिप्शन पूरे परिवार को कवर करती है — पार्टनर को भी बिना अतिरिक्त शुल्क के एक्सेस।', id:'PlayOneVideo dimulai dengan uji coba gratis 14 hari, lalu €1,99 per bulan. Satu langganan mencakup seluruh keluarga — pasangan juga mendapat akses tanpa biaya tambahan.' },

    faq4Q: { en:'Does PlayOneVideo collect data about my child?', nl:'Verzamelt PlayOneVideo gegevens over mijn kind?', de:'Sammelt PlayOneVideo Daten über mein Kind?', fr:'PlayOneVideo collecte-t-il des données sur mon enfant ?', es:'¿PlayOneVideo recopila datos sobre mi hijo?', it:'PlayOneVideo raccoglie dati su mio figlio?', pt:'O PlayOneVideo coleta dados sobre meu filho?', ru:'Собирает ли PlayOneVideo данные о моём ребёнке?', ar:'هل يجمع PlayOneVideo بيانات عن طفلي؟', zh:'PlayOneVideo会收集我孩子的数据吗？', ja:'PlayOneVideoは子供のデータを収集しますか？', ko:'PlayOneVideo가 내 아이에 대한 데이터를 수집하나요?', hi:'क्या PlayOneVideo मेरे बच्चे के बारे में डेटा एकत्र करता है?', id:'Apakah PlayOneVideo mengumpulkan data tentang anak saya?' },
    faq4A: { en:'No. PlayOneVideo only stores a user ID, a nickname for your child, and their saved video list. No personal data, no behavioral tracking, no ads.', nl:'Nee. PlayOneVideo slaat alleen een gebruikers-ID, een bijnaam voor je kind en hun videolijst op. Geen persoonsgegevens, geen gedragsregistratie, geen reclame.', de:'Nein. PlayOneVideo speichert nur eine Benutzer-ID, einen Spitznamen für dein Kind und ihre Videoliste. Keine persönlichen Daten, kein Verhaltens-Tracking, keine Werbung.', fr:'Non. PlayOneVideo ne stocke qu\'un identifiant utilisateur, un surnom pour votre enfant et leur liste de vidéos. Aucune donnée personnelle, aucun suivi comportemental, aucune publicité.', es:'No. PlayOneVideo solo almacena un ID de usuario, un apodo para tu hijo y su lista de vídeos. Sin datos personales, sin seguimiento del comportamiento, sin anuncios.', it:'No. PlayOneVideo memorizza solo un ID utente, un soprannome per il bambino e la loro lista di video. Nessun dato personale, nessun tracciamento, nessuna pubblicità.', pt:'Não. PlayOneVideo armazena apenas um ID de usuário, um apelido para seu filho e a lista de vídeos. Sem dados pessoais, sem rastreamento comportamental, sem anúncios.', ru:'Нет. PlayOneVideo хранит только идентификатор пользователя, псевдоним ребёнка и список сохранённых видео. Никаких личных данных, поведенческого отслеживания или рекламы.', ar:'لا. يخزن PlayOneVideo فقط معرف المستخدم ولقب طفلك وقائمة مقاطعهم. لا بيانات شخصية، لا تتبع سلوكي، لا إعلانات.', zh:'不会。PlayOneVideo只存储用户ID、孩子的昵称和视频列表。没有个人数据，没有行为追踪，没有广告。', ja:'いいえ。PlayOneVideoはユーザーID、子供のニックネーム、保存した動画リストのみを保存します。個人データなし、行動追跡なし、広告なし。', ko:'아니요. PlayOneVideo는 사용자 ID, 아이의 닉네임, 저장된 동영상 목록만 저장합니다. 개인 데이터 없음, 행동 추적 없음, 광고 없음.', hi:'नहीं। PlayOneVideo केवल एक उपयोगकर्ता ID, बच्चे का उपनाम और वीडियो सूची संग्रहीत करता है। कोई व्यक्तिगत डेटा नहीं, कोई ट्रैकिंग नहीं, कोई विज्ञापन नहीं।', id:'Tidak. PlayOneVideo hanya menyimpan ID pengguna, nama panggilan anak, dan daftar video tersimpan. Tidak ada data pribadi, tidak ada pelacakan, tidak ada iklan.' },

    faq5Q: { en:'Which phones does it work on?', nl:'Op welke telefoons werkt het?', de:'Auf welchen Geräten funktioniert es?', fr:'Sur quels appareils fonctionne-t-il ?', es:'¿En qué dispositivos funciona?', it:'Su quali dispositivi funziona?', pt:'Em quais dispositivos funciona?', ru:'На каких устройствах работает?', ar:'على أي أجهزة يعمل؟', zh:'在哪些设备上可以使用？', ja:'どの端末で使えますか？', ko:'어떤 기기에서 사용할 수 있나요?', hi:'यह किन डिवाइस पर काम करता है?', id:'Di perangkat apa saja ini bekerja?' },
    faq5A: { en:'PlayOneVideo is currently available on iPhone and iPad (iOS). An Android version is in development and coming soon.', nl:'PlayOneVideo is momenteel beschikbaar op iPhone en iPad (iOS). Een Android-versie is in ontwikkeling en komt binnenkort.', de:'PlayOneVideo ist derzeit für iPhone und iPad (iOS) verfügbar. Eine Android-Version ist in Entwicklung und kommt bald.', fr:'PlayOneVideo est actuellement disponible sur iPhone et iPad (iOS). Une version Android est en cours de développement et arrive bientôt.', es:'PlayOneVideo está disponible actualmente en iPhone y iPad (iOS). Una versión para Android está en desarrollo y llegará pronto.', it:'PlayOneVideo è attualmente disponibile su iPhone e iPad (iOS). Una versione Android è in sviluppo e arriverà presto.', pt:'PlayOneVideo está disponível atualmente no iPhone e iPad (iOS). Uma versão para Android está em desenvolvimento e chegará em breve.', ru:'PlayOneVideo сейчас доступен на iPhone и iPad (iOS). Версия для Android находится в разработке и скоро появится.', ar:'PlayOneVideo متاح حالياً على iPhone وiPad (iOS). نسخة Android قيد التطوير وستصدر قريباً.', zh:'PlayOneVideo目前适用于iPhone和iPad（iOS）。Android版本正在开发中，即将推出。', ja:'PlayOneVideoは現在iPhone・iPad（iOS）でご利用いただけます。Android版は開発中で、近日公開予定です。', ko:'PlayOneVideo는 현재 iPhone과 iPad(iOS)에서 이용 가능합니다. Android 버전은 개발 중이며 곧 출시됩니다.', hi:'PlayOneVideo अभी iPhone और iPad (iOS) पर उपलब्ध है। Android वर्शन विकास में है और जल्द आ रहा है।', id:'PlayOneVideo saat ini tersedia di iPhone dan iPad (iOS). Versi Android sedang dikembangkan dan akan segera hadir.' },

    /* ── affiliate page ── */
    affLabel: { en:'Affiliate program', nl:'Affiliate programma', de:'Affiliate-Programm', fr:'Programme d\'affiliation', es:'Programa de afiliados', it:'Programma di affiliazione', pt:'Programa de afiliados', ru:'Партнёрская программа', ar:'برنامج الشراكة', zh:'联盟计划', ja:'アフィリエイトプログラム', ko:'제휴 프로그램', hi:'एफिलिएट प्रोग्राम', id:'Program afiliasi' },
    affHeading: { en:'Tell other parents. Earn from it.', nl:'Vertel het andere ouders. Verdien eraan.', de:'Erzähl es anderen Eltern. Verdien daran.', fr:'Parlez-en aux autres parents. Gagnez-y.', es:'Cuéntaselo a otros padres. Gana con ello.', it:'Parlane ad altri genitori. Guadagnaci.', pt:'Conte a outros pais. Ganhe com isso.', ru:'Расскажите другим родителям. Зарабатывайте на этом.', ar:'أخبر الآباء الآخرين. واكسب من ذلك.', zh:'告诉其他家长，赚取佣金。', ja:'他の親に伝えて、報酬を得ましょう。', ko:'다른 부모에게 알리고 수익을 얻으세요.', hi:'दूसरे माता-पिता को बताएं। इससे कमाएं।', id:'Beri tahu orang tua lain. Dapatkan komisinya.' },
    affIntro: { en:'Are you a blogger, influencer or active in a parent community? Promote PlayOneVideo and earn commission on every paying subscriber you refer, for the first 7 months.', nl:'Ben je blogger, influencer of actief in een oudercommunity? Promoot PlayOneVideo en verdien commissie op elke betalende abonnee die je aanbrengt, de eerste 7 maanden lang.', de:'Bist du Blogger, Influencer oder in einer Eltern-Community aktiv? Bewirb PlayOneVideo und verdiene Provision für jeden zahlenden Abonnenten, den du vermittelst, in den ersten 7 Monaten.', fr:'Vous êtes blogueur, influenceur ou actif dans une communauté de parents ? Faites la promotion de PlayOneVideo et gagnez une commission sur chaque abonné payant que vous parrainez, pendant les 7 premiers mois.', es:'¿Eres bloguero, influencer o activo en una comunidad de padres? Promociona PlayOneVideo y gana comisión por cada suscriptor de pago que recomiendes, durante los primeros 7 meses.', it:'Sei blogger, influencer o attivo in una community di genitori? Promuovi PlayOneVideo e guadagna una commissione su ogni abbonato pagante che porti, per i primi 7 mesi.', pt:'É blogueiro, influenciador ou ativo numa comunidade de pais? Promova o PlayOneVideo e ganhe comissão por cada assinante pagante que indicar, durante os primeiros 7 meses.', ru:'Вы блогер, инфлюенсер или активны в родительском сообществе? Продвигайте PlayOneVideo и получайте комиссию за каждого платящего подписчика, которого вы привели, в течение первых 7 месяцев.', ar:'هل أنت مدوّن أو مؤثّر أو ناشط في مجتمع للآباء؟ روّج لتطبيق PlayOneVideo واكسب عمولة عن كل مشترك مدفوع تجلبه، خلال الأشهر السبعة الأولى.', zh:'你是博主、网红或活跃于家长社群吗？推广 PlayOneVideo，为你推荐的每位付费订阅者赚取佣金，持续前 7 个月。', ja:'ブロガー、インフルエンサー、または親のコミュニティで活動していますか？PlayOneVideo を紹介して、あなたが獲得した有料登録者ごとに最初の7か月間コミッションを得られます。', ko:'블로거, 인플루언서 또는 부모 커뮤니티에서 활동하시나요? PlayOneVideo를 홍보하고 추천한 유료 구독자마다 첫 7개월 동안 커미션을 받으세요.', hi:'क्या आप ब्लॉगर, इन्फ्लुएंसर हैं या पैरेंट कम्युनिटी में सक्रिय हैं? PlayOneVideo का प्रचार करें और पहले 7 महीनों तक आपके द्वारा रेफ़र किए गए हर पेइंग सब्सक्राइबर पर कमीशन कमाएं।', id:'Apakah Anda blogger, influencer, atau aktif di komunitas orang tua? Promosikan PlayOneVideo dan dapatkan komisi untuk setiap pelanggan berbayar yang Anda rekomendasikan, selama 7 bulan pertama.' },
    affUspLabel: { en:'Extra benefit for your community', nl:'Extra voordeel voor je community', de:'Extra-Vorteil für deine Community', fr:'Avantage supplémentaire pour votre communauté', es:'Ventaja extra para tu comunidad', it:'Vantaggio extra per la tua community', pt:'Benefício extra para a sua comunidade', ru:'Дополнительный бонус для вашего сообщества', ar:'ميزة إضافية لمجتمعك', zh:'为你的社群带来额外福利', ja:'あなたのコミュニティへの特典', ko:'커뮤니티를 위한 추가 혜택', hi:'आपकी कम्युनिटी के लिए अतिरिक्त फायदा', id:'Manfaat ekstra untuk komunitas Anda' },
    affUspHeadline: { en:'6 weeks free via your code', nl:'6 weken gratis via jouw code', de:'6 Wochen gratis über deinen Code', fr:'6 semaines gratuites avec votre code', es:'6 semanas gratis con tu código', it:'6 settimane gratis con il tuo codice', pt:'6 semanas grátis com o seu código', ru:'6 недель бесплатно по вашему коду', ar:'6 أسابيع مجانية عبر رمزك', zh:'用你的代码享 6 周免费', ja:'あなたのコードで6週間無料', ko:'당신의 코드로 6주 무료', hi:'आपके कोड से 6 हफ्ते मुफ्त', id:'6 minggu gratis lewat kode Anda' },
    affUspBody: { en:'Followers who enter your promo code get a 14-day App Store trial plus a 1-month bonus via the partner boost. Stronger story, higher conversion, more commission for you.', nl:'Volgers die jouw promocode invoeren krijgen een proefperiode van 14 dagen via de App Store plus 1 maand bonus via de partnerboost. Sterker verhaal, hogere conversie, meer commissie voor jou.', de:'Follower, die deinen Promo-Code eingeben, erhalten 14 Tage Testzeitraum über den App Store plus 1 Monat Bonus durch den Partner-Boost. Stärkere Story, höhere Conversion, mehr Provision für dich.', fr:'Les abonnés qui saisissent votre code promo obtiennent un essai de 14 jours via l\'App Store plus 1 mois de bonus grâce au boost partenaire. Récit plus fort, meilleure conversion, plus de commission pour vous.', es:'Los seguidores que introduzcan tu código promocional obtienen una prueba de 14 días en la App Store más 1 mes de bonus con el partner boost. Mensaje más fuerte, más conversión, más comisión para ti.', it:'I follower che inseriscono il tuo codice promo ottengono una prova di 14 giorni tramite l\'App Store più 1 mese di bonus con il partner boost. Racconto più forte, conversione più alta, più commissioni per te.', pt:'Os seguidores que introduzem o seu código promocional recebem um teste de 14 dias na App Store mais 1 mês de bónus através do partner boost. História mais forte, conversão maior, mais comissão para si.', ru:'Подписчики, вводящие ваш промокод, получают 14-дневный пробный период в App Store плюс 1 месяц бонуса через партнёрский буст. Сильнее история, выше конверсия, больше комиссии для вас.', ar:'المتابعون الذين يُدخلون رمزك الترويجي يحصلون على تجربة مدتها 14 يومًا عبر App Store بالإضافة إلى شهر إضافي كمكافأة شراكة. قصة أقوى، تحويل أعلى، وعمولة أكبر لك.', zh:'输入你的推广码的粉丝可获得 App Store 14 天试用，外加合作伙伴额外赠送 1 个月。故事更有说服力，转化更高，你的佣金更多。', ja:'あなたのプロモコードを入力したフォロワーは、App Store の14日間無料トライアルに加え、パートナーブーストで1か月のボーナスを獲得します。説得力が増し、コンバージョンが上がり、あなたの報酬も増えます。', ko:'당신의 프로모 코드를 입력한 팔로워는 App Store 14일 체험에 파트너 부스트로 1개월 보너스까지 받습니다. 더 강한 스토리, 더 높은 전환율, 더 많은 커미션.', hi:'आपका प्रोमो कोड डालने वाले फॉलोअर्स को 14 दिन का App Store ट्रायल और पार्टनर बूस्ट से 1 महीने का बोनस मिलता है। मजबूत कहानी, ज्यादा कन्वर्जन, आपके लिए ज्यादा कमीशन।', id:'Pengikut yang memasukkan kode promo Anda mendapat uji coba 14 hari lewat App Store plus bonus 1 bulan lewat partner boost. Cerita lebih kuat, konversi lebih tinggi, komisi lebih besar untuk Anda.' },
    affCalcLabel: { en:'What does it pay?', nl:'Wat levert het op?', de:'Was bringt es?', fr:'Combien ça rapporte ?', es:'¿Cuánto paga?', it:'Quanto rende?', pt:'Quanto rende?', ru:'Сколько вы заработаете?', ar:'كم يدرّ من ربح؟', zh:'能赚多少？', ja:'いくら稼げる？', ko:'수익은 얼마인가요?', hi:'इससे कितना मिलता है?', id:'Berapa hasilnya?' },
    affCalcSubscription: { en:'Subscription', nl:'Abonnement', de:'Abonnement', fr:'Abonnement', es:'Suscripción', it:'Abbonamento', pt:'Assinatura', ru:'Подписка', ar:'الاشتراك', zh:'订阅', ja:'サブスクリプション', ko:'구독', hi:'सब्सक्रिप्शन', id:'Langganan' },
    affCalcSubscriptionValue: { en:'€1.99 per month', nl:'€1,99 per maand', de:'€1,99 pro Monat', fr:'1,99 € par mois', es:'€1,99 al mes', it:'€1,99 al mese', pt:'€1,99 por mês', ru:'€1,99 в месяц', ar:'€1,99 شهريًا', zh:'每月 €1,99', ja:'月額 €1,99', ko:'월 €1,99', hi:'€1,99 प्रति माह', id:'€1,99 per bulan' },
    affCalcCommission: { en:'App Store commission (Apple)', nl:'App Store commissie (Apple)', de:'App Store Provision (Apple)', fr:'Commission App Store (Apple)', es:'Comisión de App Store (Apple)', it:'Commissione App Store (Apple)', pt:'Comissão da App Store (Apple)', ru:'Комиссия App Store (Apple)', ar:'عمولة App Store (آبل)', zh:'App Store 佣金（Apple）', ja:'App Store 手数料（Apple）', ko:'App Store 수수료 (Apple)', hi:'App Store कमीशन (Apple)', id:'Komisi App Store (Apple)' },
    affCalcShare: { en:'Your share', nl:'Jouw aandeel', de:'Dein Anteil', fr:'Votre part', es:'Tu parte', it:'La tua quota', pt:'A sua parte', ru:'Ваша доля', ar:'حصتك', zh:'你的分成', ja:'あなたの取り分', ko:'당신의 몫', hi:'आपका हिस्सा', id:'Bagian Anda' },
    affCalcShareValue: { en:'50% of net', nl:'50% van netto', de:'50% vom Netto', fr:'50 % du net', es:'50% del neto', it:'50% del netto', pt:'50% do líquido', ru:'50% от чистой суммы', ar:'50٪ من الصافي', zh:'净收入的 50%', ja:'純収益の50%', ko:'순액의 50%', hi:'शुद्ध राशि का 50%', id:'50% dari nett' },
    affCalcPeriod: { en:'Period per subscriber', nl:'Periode per abonnee', de:'Zeitraum pro Abonnent', fr:'Durée par abonné', es:'Periodo por suscriptor', it:'Periodo per abbonato', pt:'Período por assinante', ru:'Период на подписчика', ar:'المدة لكل مشترك', zh:'每位订阅者的周期', ja:'登録者ごとの期間', ko:'구독자당 기간', hi:'प्रति सब्सक्राइबर अवधि', id:'Periode per pelanggan' },
    affCalcPeriodValue: { en:'First 7 months', nl:'Eerste 7 maanden', de:'Erste 7 Monate', fr:'7 premiers mois', es:'Primeros 7 meses', it:'Primi 7 mesi', pt:'Primeiros 7 meses', ru:'Первые 7 месяцев', ar:'أول 7 أشهر', zh:'前 7 个月', ja:'最初の7か月', ko:'첫 7개월', hi:'पहले 7 महीने', id:'7 bulan pertama' },
    affCalcTotal: { en:'Total per subscriber', nl:'Totaal per abonnee', de:'Gesamt pro Abonnent', fr:'Total par abonné', es:'Total por suscriptor', it:'Totale per abbonato', pt:'Total por assinante', ru:'Итого на подписчика', ar:'الإجمالي لكل مشترك', zh:'每位订阅者总计', ja:'登録者あたりの合計', ko:'구독자당 총액', hi:'प्रति सब्सक्राइबर कुल', id:'Total per pelanggan' },
    affCalcTotalValue: { en:'approx. €5.00', nl:'ca. €5,00', de:'ca. €5,00', fr:'env. 5,00 €', es:'aprox. €5,00', it:'circa €5,00', pt:'aprox. €5,00', ru:'около €5,00', ar:'حوالي €5,00', zh:'约 €5,00', ja:'約 €5,00', ko:'약 €5,00', hi:'लगभग €5,00', id:'sekitar €5,00' },
    affCalcPlayStoreNote: { en:'Via the Play Store (Google) Apple\'s commission is 15% instead of 30%, making the total per subscriber approx. €5.90. The exact commission may vary per platform.', nl:'Via de Play Store (Google) is de commissie 15% in plaats van 30%, waardoor het totaal per abonnee ca. €5,90 is. De exacte commissie kan per platform verschillen.', de:'Über den Play Store (Google) beträgt die Provision 15% statt 30%, wodurch der Gesamtbetrag pro Abonnent ca. €5,90 beträgt. Die genaue Provision kann je nach Plattform variieren.', fr:'Via le Play Store (Google), la commission est de 15 % au lieu de 30 %, ce qui porte le total par abonné à env. 5,90 €. La commission exacte peut varier selon la plateforme.', es:'A través de Play Store (Google) la comisión es del 15% en lugar del 30%, lo que hace que el total por suscriptor sea de aprox. €5,90. La comisión exacta puede variar según la plataforma.', it:'Tramite il Play Store (Google) la commissione è del 15% invece del 30%, portando il totale per abbonato a circa €5,90. La commissione esatta può variare a seconda della piattaforma.', pt:'Através da Play Store (Google) a comissão é de 15% em vez de 30%, o que faz com que o total por assinante seja aprox. €5,90. A comissão exata pode variar por plataforma.', ru:'Через Play Store (Google) комиссия составляет 15% вместо 30%, поэтому итог на подписчика около €5,90. Точная комиссия может отличаться в зависимости от платформы.', ar:'عبر Play Store (جوجل) تكون العمولة 15٪ بدلاً من 30٪، مما يجعل الإجمالي لكل مشترك حوالي €5,90. قد تختلف العمولة الدقيقة حسب المنصة.', zh:'通过 Play Store（Google）佣金为 15% 而非 30%，因此每位订阅者总计约 €5,90。具体佣金可能因平台而异。', ja:'Play Store（Google）経由では手数料は30%ではなく15%となり、登録者あたりの合計は約 €5,90 になります。正確な手数料はプラットフォームによって異なる場合があります。', ko:'Play Store(Google)를 통하면 수수료가 30% 대신 15%이므로 구독자당 총액은 약 €5,90입니다. 정확한 수수료는 플랫폼에 따라 다를 수 있습니다.', hi:'Play Store (Google) के जरिए कमीशन 30% की जगह 15% होता है, जिससे प्रति सब्सक्राइबर कुल लगभग €5,90 बनता है। सटीक कमीशन प्लेटफॉर्म के अनुसार अलग हो सकता है।', id:'Melalui Play Store (Google) komisi Apple adalah 15% bukan 30%, sehingga total per pelanggan sekitar €5,90. Komisi pasti dapat berbeda per platform.' },
    affFeat1Title: { en:'Your own promo code', nl:'Je eigen promocode', de:'Dein eigener Promo-Code', fr:'Votre propre code promo', es:'Tu propio código promocional', it:'Il tuo codice promo personale', pt:'O seu próprio código promocional', ru:'Ваш собственный промокод', ar:'رمزك الترويجي الخاص', zh:'你的专属推广码', ja:'あなた専用のプロモコード', ko:'나만의 프로모 코드', hi:'आपका अपना प्रोमो कोड', id:'Kode promo milik Anda sendiri' },
    affFeat1Body: { en:'You get a unique code based on your name. New subscribers enter it when signing up.', nl:'Je krijgt een unieke code op basis van je naam. Nieuwe abonnees voeren die in bij het aanmelden.', de:'Du erhältst einen eindeutigen Code basierend auf deinem Namen. Neue Abonnenten geben ihn bei der Anmeldung ein.', fr:'Vous recevez un code unique basé sur votre nom. Les nouveaux abonnés le saisissent lors de l\'inscription.', es:'Obtienes un código único basado en tu nombre. Los nuevos suscriptores lo introducen al registrarse.', it:'Ricevi un codice unico basato sul tuo nome. I nuovi abbonati lo inseriscono in fase di registrazione.', pt:'Recebe um código único baseado no seu nome. Os novos assinantes introduzem-no ao registar-se.', ru:'Вы получаете уникальный код, основанный на вашем имени. Новые подписчики вводят его при регистрации.', ar:'تحصل على رمز فريد مبني على اسمك. يُدخله المشتركون الجدد عند التسجيل.', zh:'你将获得一个以你名字为基础的唯一代码。新订阅者注册时输入它。', ja:'あなたの名前をもとにしたユニークなコードを発行します。新規登録者は登録時に入力します。', ko:'당신의 이름을 바탕으로 한 고유 코드를 받습니다. 새 구독자는 가입 시 이 코드를 입력합니다.', hi:'आपको आपके नाम पर आधारित एक यूनीक कोड मिलता है। नए सब्सक्राइबर साइन अप करते समय इसे डालते हैं।', id:'Anda mendapat kode unik berdasarkan nama Anda. Pelanggan baru memasukkannya saat mendaftar.' },
    affFeat2Title: { en:'Active immediately', nl:'Direct actief', de:'Sofort aktiv', fr:'Actif immédiatement', es:'Activo de inmediato', it:'Attivo subito', pt:'Ativo de imediato', ru:'Активно сразу', ar:'مفعّل فورًا', zh:'立即生效', ja:'すぐに有効', ko:'즉시 활성화', hi:'तुरंत सक्रिय', id:'Aktif seketika' },
    affFeat2Body: { en:'After signing up you are active as an affiliate partner right away. No waiting time.', nl:'Na aanmelden ben je meteen actief als affiliate partner. Geen wachttijd.', de:'Nach der Anmeldung bist du sofort als Affiliate-Partner aktiv. Keine Wartezeit.', fr:'Après votre inscription, vous êtes immédiatement actif en tant que partenaire affilié. Aucun délai.', es:'Tras registrarte, quedas activo como socio afiliado al instante. Sin tiempos de espera.', it:'Dopo la registrazione sei subito attivo come partner affiliato. Nessun tempo di attesa.', pt:'Depois de se inscrever, fica ativo como parceiro afiliado de imediato. Sem tempo de espera.', ru:'После регистрации вы сразу становитесь активным партнёром. Без ожидания.', ar:'بعد التسجيل تصبح نشطًا كشريك تسويق فورًا. بدون فترة انتظار.', zh:'注册后立即成为有效的联盟合作伙伴，无需等待。', ja:'登録後すぐにアフィリエイトパートナーとしてアクティブになります。待ち時間なし。', ko:'가입 후 곧바로 제휴 파트너로 활성화됩니다. 대기 시간 없음.', hi:'साइन अप करते ही आप एफिलिएट पार्टनर के तौर पर सक्रिय हो जाते हैं। कोई प्रतीक्षा नहीं।', id:'Setelah mendaftar Anda langsung aktif sebagai mitra afiliasi. Tanpa masa tunggu.' },
    affFeat3Title: { en:'Monthly payout', nl:'Maandelijkse uitbetaling', de:'Monatliche Auszahlung', fr:'Paiement mensuel', es:'Pago mensual', it:'Pagamento mensile', pt:'Pagamento mensal', ru:'Ежемесячная выплата', ar:'دفع شهري', zh:'每月结算', ja:'毎月のお支払い', ko:'매월 지급', hi:'मासिक भुगतान', id:'Pembayaran bulanan' },
    affFeat3Body: { en:'Commission is paid monthly via bank transfer to the IBAN you provide.', nl:'De commissie wordt maandelijks per bankoverschrijving uitbetaald op het IBAN dat je opgeeft.', de:'Die Provision wird monatlich per Banküberweisung auf die von dir angegebene IBAN ausgezahlt.', fr:'La commission est versée chaque mois par virement bancaire sur l\'IBAN que vous indiquez.', es:'La comisión se paga mensualmente mediante transferencia bancaria al IBAN que facilites.', it:'La commissione viene pagata ogni mese tramite bonifico sull\'IBAN che fornisci.', pt:'A comissão é paga mensalmente por transferência bancária para o IBAN que indicar.', ru:'Комиссия выплачивается ежемесячно банковским переводом на указанный вами IBAN.', ar:'تُدفع العمولة شهريًا عبر تحويل بنكي إلى رقم IBAN الذي تقدّمه.', zh:'佣金每月通过银行转账汇至你提供的 IBAN 账户。', ja:'コミッションは毎月、ご指定の IBAN への銀行振込で支払われます。', ko:'커미션은 매월 제공하신 IBAN으로 계좌이체로 지급됩니다.', hi:'कमीशन हर महीने आपके दिए गए IBAN पर बैंक ट्रांसफर से भेजा जाता है।', id:'Komisi dibayarkan setiap bulan melalui transfer bank ke IBAN yang Anda berikan.' },
    affFeat4Title: { en:'No subscription needed', nl:'Geen abonnement nodig', de:'Kein Abo erforderlich', fr:'Aucun abonnement requis', es:'No necesitas suscripción', it:'Nessun abbonamento richiesto', pt:'Não precisa de assinatura', ru:'Подписка не нужна', ar:'لا حاجة لاشتراك', zh:'无需订阅', ja:'サブスクリプション不要', ko:'구독 필요 없음', hi:'सब्सक्रिप्शन की जरूरत नहीं', id:'Tanpa perlu langganan' },
    affFeat4Body: { en:'Signing up as an affiliate is free, via the app.', nl:'Aanmelden als affiliate is gratis, via de app.', de:'Die Anmeldung als Affiliate ist kostenlos, direkt über die App.', fr:'L\'inscription comme affilié est gratuite, via l\'application.', es:'Registrarse como afiliado es gratis, desde la app.', it:'L\'iscrizione come affiliato è gratuita, tramite l\'app.', pt:'Inscrever-se como afiliado é grátis, através da app.', ru:'Регистрация в партнёрской программе бесплатна, через приложение.', ar:'التسجيل كشريك تسويق مجاني، عبر التطبيق.', zh:'通过 App 免费注册成为联盟伙伴。', ja:'アフィリエイト登録はアプリから無料で行えます。', ko:'제휴 파트너 가입은 앱을 통해 무료입니다.', hi:'एफिलिएट के तौर पर साइन अप करना मुफ्त है, ऐप के जरिए।', id:'Mendaftar sebagai afiliasi gratis, lewat aplikasi.' },
    affCallout: { en:'Sign up via the app. Download PlayOneVideo, open Settings and choose Become affiliate partner. You are active right after.', nl:'Meld je aan via de app. Download PlayOneVideo, open Instellingen en kies Word affiliate partner. Daarna ben je direct actief.', de:'Melde dich über die App an. Lade PlayOneVideo herunter, öffne die Einstellungen und wähle Affiliate-Partner werden. Danach bist du sofort aktiv.', fr:'Inscrivez-vous via l\'application. Téléchargez PlayOneVideo, ouvrez les Réglages et choisissez Devenir partenaire affilié. Vous êtes actif immédiatement.', es:'Regístrate desde la app. Descarga PlayOneVideo, abre Ajustes y elige Hazte socio afiliado. Quedas activo al instante.', it:'Iscriviti tramite l\'app. Scarica PlayOneVideo, apri le Impostazioni e scegli Diventa partner affiliato. Sei subito attivo.', pt:'Inscreva-se através da app. Descarregue o PlayOneVideo, abra as Definições e escolha Tornar-se parceiro afiliado. Fica ativo logo a seguir.', ru:'Регистрируйтесь через приложение. Скачайте PlayOneVideo, откройте Настройки и выберите Стать партнёром. Сразу после этого вы активны.', ar:'سجّل عبر التطبيق. نزّل PlayOneVideo، افتح الإعدادات واختر كن شريكًا تسويقيًا. ستكون مفعّلًا مباشرةً بعد ذلك.', zh:'通过 App 注册。下载 PlayOneVideo，打开"设置"，选择"成为联盟伙伴"，注册后立即生效。', ja:'アプリから登録してください。PlayOneVideo をダウンロードし、設定を開いて「アフィリエイトパートナーになる」を選択します。直後にアクティブになります。', ko:'앱에서 가입하세요. PlayOneVideo를 다운로드한 뒤 설정을 열고 제휴 파트너 되기를 선택하세요. 바로 활성화됩니다.', hi:'ऐप के जरिए साइन अप करें। PlayOneVideo डाउनलोड करें, सेटिंग्स खोलें और एफिलिएट पार्टनर बनें चुनें। इसके तुरंत बाद आप सक्रिय हो जाते हैं।', id:'Daftar lewat aplikasi. Unduh PlayOneVideo, buka Pengaturan dan pilih Jadi mitra afiliasi. Anda langsung aktif setelahnya.' },
  };

  function getLang() {
    // 1. URL-path heeft voorrang: /nl/, /de/ etc. (zie build.js voor gegenereerde subpaths)
    const pathMatch = location.pathname.match(/^\/([a-z]{2})(\/|$)/i);
    if (pathMatch) {
      const code = pathMatch[1].toLowerCase();
      if (T.navAffiliate[code]) return code;
    }
    // 2. Handmatige keuze via selector
    const saved = localStorage.getItem('pov_lang');
    if (saved && T.navAffiliate[saved]) return saved;
    // 3. Browser default
    const browser = (navigator.language || 'en').substring(0, 2).toLowerCase();
    return T.navAffiliate[browser] ? browser : 'en';
  }

  function applyLang(lang) {
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (T[key] && T[key][lang] !== undefined) {
        el.textContent = T[key][lang];
      }
    });
    // Update select
    const sel = document.getElementById('lang-select');
    if (sel) sel.value = lang;
  }

  // Bepaalt de URL waar de switcher naartoe moet als de gebruiker een andere
  // taal kiest. Homepage en affiliate bestaan in alle 14 talen; privacy/terms
  // alleen in EN (root) en NL (/nl/). Voor andere talen op privacy/terms valt
  // de switcher terug op tekst-vervanging (return null).
  function targetUrlForLang(lang) {
    const path = location.pathname;
    // Homepage: / of /{lang}/
    if (path === '/' || path === '/index.html' ||
        /^\/[a-z]{2}\/?$/i.test(path) || /^\/[a-z]{2}\/index\.html$/i.test(path)) {
      return lang === 'en' ? '/' : '/' + lang + '/';
    }
    // Affiliate: /affiliate.html of /{lang}/affiliate.html
    if (path === '/affiliate.html' || /^\/[a-z]{2}\/affiliate\.html$/i.test(path)) {
      return lang === 'en' ? '/affiliate.html' : '/' + lang + '/affiliate.html';
    }
    // Privacy en terms: alleen EN en NL hebben pagina's. Andere talen: null.
    if (path === '/privacy.html' || path === '/nl/privacy.html') {
      if (lang === 'en') return '/privacy.html';
      if (lang === 'nl') return '/nl/privacy.html';
      return null;
    }
    if (path === '/terms.html' || path === '/nl/terms.html') {
      if (lang === 'en') return '/terms.html';
      if (lang === 'nl') return '/nl/terms.html';
      return null;
    }
    return null;
  }

  function buildSelector() {
    const sel = document.createElement('select');
    sel.id = 'lang-select';
    sel.style.cssText = 'background:transparent;border:none;font-size:13px;font-weight:500;color:var(--muted);cursor:pointer;font-family:inherit;padding:2px 4px;border-radius:4px;';
    sel.title = 'Language';
    Object.entries(LANGS).forEach(([code, name]) => {
      const opt = document.createElement('option');
      opt.value = code;
      opt.textContent = name;
      sel.appendChild(opt);
    });
    sel.value = getLang();
    sel.addEventListener('change', () => {
      const newLang = sel.value;
      try { localStorage.setItem('pov_lang', newLang); } catch (e) {}
      const target = targetUrlForLang(newLang);
      if (target) {
        const currentNormalized = location.pathname.replace(/index\.html$/, '');
        if (target !== location.pathname && target !== currentNormalized) {
          location.href = target;
          return;
        }
      }
      applyLang(newLang);
    });
    return sel;
  }

  // Browser: mount selector + apply language on ready.
  if (typeof document !== 'undefined') {
    document.addEventListener('DOMContentLoaded', () => {
      const navLinks = document.querySelector('.nav-links');
      if (navLinks) {
        const li = document.createElement('li');
        li.appendChild(buildSelector());
        navLinks.appendChild(li);
      }
      applyLang(getLang());
    });
  }

  // Node (build.js): exporteer T + LANGS zodat subpaths gegenereerd kunnen worden.
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { T, LANGS };
  }
})(typeof globalThis !== 'undefined' ? globalThis : this);
